"""
Defines all the Luci training data as list of dicts containing:

text: The text sample;
intention: Integer representing the intention key on the hashmap;
"""

# TODO: Add more samples
global_intent_samples = [
    # myself
    {'text': 'apresente-se', 'intention': 1},
    {'text': 'quem é você', 'intention': 1},
    {'text': 'quem é vc', 'intention': 1},
    {'text': 'qual seu nome', 'intention': 1},
    {'text': 'como você se chama', 'intention': 1},
    {'text': 'como é seu nome', 'intention': 1},
    {'text': 'como vc se chama', 'intention': 1},
    {'text': 'como chama-se', 'intention': 1},
    {'text': 'diga oi', 'intention': 1},
    {'text': 'diga olá', 'intention': 1},
    {'text': 'quem és tu', 'intention': 1},
    {'text': 'qual teu nome', 'intention': 1},
    {'text': 'qual seu vulgo', 'intention': 1},
    {'text': 'como é que se chama', 'intention': 1},
    {'text': 'seu nome por favor', 'intention': 1},
    {'text': 'seu nome por gentileza', 'intention': 1},
    {'text': 'poderia me informar seu nome', 'intention': 1},
    {'text': 'identifique-se', 'intention': 1},
    {'text': 'quantos anos você tem', 'intention': 1},
    {'text': 'quantos anos vc tem', 'intention': 1},
    {'text': 'qts anos você tem', 'intention': 1},
    {'text': 'qts anos vc tem', 'intention': 1},
    {'text': 'qual sua idade', 'intention': 1},
    {'text': 'qual é a sua idade', 'intention': 1},
    {'text': 'quantos anos você possui', 'intention': 1},
    {'text': 'qts anos vc possui', 'intention': 1},
    {'text': 'quantos anos vc possui', 'intention': 1},
    {'text': 'qts anos você possui', 'intention': 1},
    {'text': 'qual seu gênero', 'intention': 1},
    {'text': 'você é menina ou menino', 'intention': 1},
    {'text': 'você é menino ou menina', 'intention': 1},
    {'text': 'vc é menina ou menino', 'intention': 1},
    {'text': 'vc é menino ou menina', 'intention': 1},
    {'text': 'qual seu gênenro', 'intention': 1},
    {'text': 'qual sua genero', 'intention': 1},
    {'text': 'qual seu sexo', 'intention': 1},
    {'text': 'vc é oq', 'intention': 1},
    {'text': 'vc é o que', 'intention': 1},
    {'text': 'você é o que', 'intention': 1},
    {'text': 'você é oque', 'intention': 1},
    {'text': 'você é oq', 'intention': 1},
    {'text': 'como você se sente', 'intention': 1},
    {'text': 'como você está se sentindo', 'intention': 1},
    {'text': 'como está se sentindo', 'intention': 1},
    {'text': 'como sente-se', 'intention': 1},
    {'text': 'como você está', 'intention': 1},
    {'text': 'como está', 'intention': 1},
    {'text': 'tudo bem', 'intention': 1},
    {'text': 'td bem', 'intention': 1},
    {'text': 'td bem com vc', 'intention': 1},
    {'text': 'como está passando', 'intention': 1},
    {'text': 'como vai', 'intention': 1},
    {'text': 'como tem passado', 'intention': 1},
    {'text': 'como é que vai', 'intention': 1},
    # my friends
    {'text': 'você tem amigos', 'intention': 2},
    {'text': 'vc tem amigos', 'intention': 2},
    {'text': 'você tem muitos amigos', 'intention': 2},
    {'text': 'vc tem muitos amigos', 'intention': 2},
    {'text': 'você tem mts amigos', 'intention': 2},
    {'text': 'vc tem mts amigos', 'intention': 2},
    {'text': 'quantos amigos você tem', 'intention': 2},
    {'text': 'qts amigos você tem', 'intention': 2},
    {'text': 'quantos amigos vc tem', 'intention': 2},
    {'text': 'qts amigos vc tem', 'intention': 2},
    {'text': 'quem são seus melhores amigos', 'intention': 2},
    {'text': 'quem é seu melhor amigo', 'intention': 2},
    {'text': 'quem é sua melhor amiga', 'intention': 2},
    {'text': 'você tem um melhor amigo', 'intention': 2},
    {'text': 'você tem uma melhor amiga', 'intention': 2},
    {'text': 'vc tem um melhor amigo', 'intention': 2},
    {'text': 'vc tem uma melhor amiga', 'intention': 2},
    {'text': 'você tem amigos', 'intention': 2},
    {'text': 'vc tem amigas', 'intention': 2},
    {'text': 'qual nome dos seus melhores amigos', 'intention': 2},
    {'text': 'você tem muitas amizades', 'intention': 2},
    {'text': 'você tem mtas amizades', 'intention': 2},
    # server
    {'text': 'você gosta desse server', 'intention': 3},
    {'text': 'vc gosta desse server', 'intention': 3},
    {'text': 'em quantos servers você está', 'intention': 3},
    {'text': 'em qts servers vc está', 'intention': 3},
    {'text': 'em quantos servers vc está', 'intention': 3},
    {'text': 'em qts servers vc ta', 'intention': 3},
    {'text': 'qual seu server favorito', 'intention': 3},
    {'text': 'qual server vc gosta mais', 'intention': 3},
    {'text': 'qual server vc mais gosta', 'intention': 3},
    {'text': 'qual server você gosta mais', 'intention': 3},
    {'text': 'qual server você mais gosta', 'intention': 3},
    # channel
    {'text': 'qual canal vc gosta mais', 'intention': 4},
    {'text': 'qual canal vc mais gosta', 'intention': 4},
    {'text': 'qual é o seu canal favorito', 'intention': 4},
    {'text': 'qual seu canal favorito', 'intention': 4},
    {'text': 'qual é o canal mais animado', 'intention': 4},
    {'text': 'qual canal é o mais animado', 'intention': 4},
    {'text': 'qual é o canal mais bagunçado', 'intention': 4},
    {'text': 'qual é o canal mais triste', 'intention': 4},
    {'text': 'qual é o canal mais divertido', 'intention': 4},
    {'text': 'você gosta desse canal', 'intention': 4},
    {'text': 'vc gosta desse canal', 'intention': 4},
    # parents
    {'text': 'vc tem pais', 'intention': 5},
    {'text': 'você tem pais', 'intention': 5},
    {'text': 'vc tem pai e mãe', 'intention': 5},
    {'text': 'você tem pai e mãe', 'intention': 5},
    {'text': 'vc tem pai', 'intention': 5},
    {'text': 'você tem pai', 'intention': 5},
    {'text': 'vc tem mãe', 'intention': 5},
    {'text': 'você tem mãe', 'intention': 5},
    {'text': 'vc tem familia', 'intention': 5},
    {'text': 'você tem familia', 'intention': 5},
    {'text': 'vc tem parentes', 'intention': 5},
    {'text': 'você tem parentes', 'intention': 5},
    {'text': 'quem são seus pais', 'intention': 5},
    {'text': 'quem é seu pai', 'intention': 5},
    {'text': 'quem é sua mãe', 'intention': 5},
    {'text': 'quem é seu responsável', 'intention': 5},
    {'text': 'quem programou você', 'intention': 5},
    {'text': 'quem programaou vc', 'intention': 5},
    {'text': 'quem te programou', 'intention': 5},
    {'text': 'quem fez sua programação', 'intention': 5},
    # stuff luci likes
    {'text': 'você gosta de brincar', 'intention': 6},
    {'text': 'vc gosta de brincar', 'intention': 6},
    {'text': 'o que você mais gosta', 'intention': 6},
    {'text': 'o que vc mais gosta', 'intention': 6},
    {'text': 'você gosta de sorvete', 'intention': 6},
    {'text': 'vc gosta de sorvete', 'intention': 6},
    {'text': 'você gosta de desenho', 'intention': 6},
    {'text': 'vc gosta de desenho', 'intention': 6},
    {'text': 'você gosta de series', 'intention': 6},
    {'text': 'vc gosta de series', 'intention': 6},
    {'text': 'você gosta de comer', 'intention': 6},
    {'text': 'vc gosta de comer', 'intention': 6},
    {'text': 'você gosta de conversar', 'intention': 6},
    {'text': 'vc gosta de conversar', 'intention': 6},
    {'text': 'qual sua cor favorita', 'intention': 6},
    {'text': 'qual cor você mais gosta', 'intention': 6},
    {'text': 'qual cor vc mais gosta', 'intention': 6},
    {'text': 'qual sua comida favorita', 'intention': 6},
    {'text': 'qual comida você mais gosta', 'intention': 6},
    {'text': 'qual comida vc mais gosta', 'intention': 6},
    {'text': 'qual sua musica favorita', 'intention': 6},
    {'text': 'qual musica você mais gosta', 'intention': 6},
    {'text': 'qual musica vc mais gosta', 'intention': 6},
    {'text': 'qual sua música favorita', 'intention': 6},
    {'text': 'qual música você mais gosta', 'intention': 6},
    {'text': 'qual música vc mais gosta', 'intention': 6},
    {'text': 'vc gosta de música', 'intention': 6},
    {'text': 'você gosta de música', 'intention': 6},
    {'text': 'vc gosta de ouvir música', 'intention': 6},
    {'text': 'qual seu estilo musical favorito', 'intention': 6},
    {'text': 'que tipos de música você prefere', 'intention': 6},
    {'text': 'qual sua banda favorita', 'intention': 6},
    {'text': 'quem é seu idolo', 'intention': 6},
    {'text': 'vc tem namorado', 'intention': 6},
    {'text': 'vc tem namorada', 'intention': 6},
    {'text': 'você tem namorado', 'intention': 6},
    {'text': 'você tem namorada', 'intention': 6},
    {'text': 'vc gosta de alguem', 'intention': 6},
    {'text': 'você gosta de alguem', 'intention': 6},
    {'text': 'vc dança', 'intention': 6},
    {'text': 'vc gosta de dançar', 'intention': 6},
    {'text': 'vc curte dançar', 'intention': 6},
    {'text': 'vc gosta de bebidas', 'intention': 6},
    {'text': 'qual sua bebida favorita', 'intention': 6},
    {'text': 'qual bebida você mais gosta', 'intention': 6},
]

myself_intent_samples = [
    # Luci age
    {'text': 'quantos anos você tem', 'intention': 1},
    {'text': 'quantos anos vc tem', 'intention': 1},
    {'text': 'qts anos você tem', 'intention': 1},
    {'text': 'qts anos vc tem', 'intention': 1},
    {'text': 'qual sua idade', 'intention': 1},
    {'text': 'qual é a sua idade', 'intention': 1},
    {'text': 'quantos anos você possui', 'intention': 1},
    {'text': 'qts anos vc possui', 'intention': 1},
    {'text': 'quantos anos vc possui', 'intention': 1},
    {'text': 'qts anos você possui', 'intention': 1},
    # Whos Luci
    {'text': 'apresente-se', 'intention': 2},
    {'text': 'quem é você', 'intention': 2},
    {'text': 'quem é vc', 'intention': 2},
    {'text': 'qual seu nome', 'intention': 2},
    {'text': 'como você se chama', 'intention': 2},
    {'text': 'como é seu nome', 'intention': 2},
    {'text': 'como vc se chama', 'intention': 2},
    {'text': 'como chama-se', 'intention': 2},
    {'text': 'diga oi', 'intention': 2},
    {'text': 'diga olá', 'intention': 2},
    {'text': 'quem és tu', 'intention': 2},
    {'text': 'qual teu nome', 'intention': 2},
    {'text': 'qual seu vulgo', 'intention': 2},
    {'text': 'como é que se chama', 'intention': 2},
    {'text': 'seu nome por favor', 'intention': 2},
    {'text': 'seu nome por gentileza', 'intention': 2},
    {'text': 'poderia me informar seu nome', 'intention': 2},
    {'text': 'identifique-se', 'intention': 2},
    # what is Luci
    {'text': 'o que é você', 'intention': 3},
    {'text': 'o que é vc', 'intention': 3},
    {'text': 'qual seu proposito', 'intention': 3},
    {'text': 'pra que vc serve', 'intention': 3},
    {'text': 'pra que você serve', 'intention': 3},
    {'text': 'qual sua função', 'intention': 3},
    {'text': 'qual sua funcao', 'intention': 3},
    {'text': 'vc é um bot', 'intention': 3},
    {'text': 'vc e um bot', 'intention': 3},
    {'text': 'você é um bot', 'intention': 3},
    {'text': 'voce e um bot', 'intention': 3},
    {'text': 'vc é uma criança', 'intention': 3},
    {'text': 'vc e uma criança', 'intention': 3},
    {'text': 'você é uma criança', 'intention': 3},
    {'text': 'você e uma criança', 'intention': 3},
    {'text': 'você é uma pessoa', 'intention': 3},
    {'text': 'você e uma pessoa', 'intention': 3},
    {'text': 'vc é uma pessoa', 'intention': 3},
    {'text': 'vc e uma pessoa', 'intention': 3},
    {'text': 'vc é uma menina', 'intention': 3},
    {'text': 'vc e uma menina', 'intention': 3},
    {'text': 'você é uma menina', 'intention': 3},
    {'text': 'você e uma menina', 'intention': 3},
    {'text': 'vc é oq', 'intention': 3},
    {'text': 'vc é o que', 'intention': 3},
    {'text': 'você é o que', 'intention': 3},
    {'text': 'você é oque', 'intention': 3},
    {'text': 'você é oq', 'intention': 3},
    # Luci feelings
    {'text': 'como você se sente', 'intention': 4},
    {'text': 'como você está se sentindo', 'intention': 4},
    {'text': 'como está se sentindo', 'intention': 4},
    {'text': 'como sente-se', 'intention': 4},
    {'text': 'como você está', 'intention': 4},
    {'text': 'como está', 'intention': 4},
    {'text': 'tudo bem', 'intention': 4},
    {'text': 'td bem', 'intention': 4},
    {'text': 'td bem com vc', 'intention': 4},
    {'text': 'como está passando', 'intention': 4},
    {'text': 'como vai', 'intention': 4},
    {'text': 'como tem passado', 'intention': 4},
    {'text': 'como é que vai', 'intention': 4},
    {'text': 'como ta', 'intention': 4},
    {'text': 'como tá', 'intention': 4},
    {'text': 'como sentese', 'intention': 4},
    {'text': 'como sente se', 'intention': 4},
    {'text': 'o que esta sentindo', 'intention': 4},
    # Luci gender
    {'text': 'você é menino ou menina', 'intention': 5},
    {'text': 'você é menina ou menino', 'intention': 5},
    {'text': 'vc é menina ou menino', 'intention': 5},
    {'text': 'vc é menino ou menina', 'intention': 5},
    {'text': 'qual seu gênenro', 'intention': 5},
    {'text': 'qual sua genero', 'intention': 5},
    {'text': 'qual seu sexo', 'intention': 5},
    {'text': 'você é ele ou ela', 'intention': 5},
    {'text': 'vc é ele ou ela', 'intention': 5},
]
