"""
Defines all the Luci training data as list of dicts containing:

text: The text sample;
intention: Integer representing the intention key on the hashmap;
"""

class IntentionSamples:
    """
    Contains all the samples for training the classification of the intentions,
    as proposed on the intention architecture on Luci docs:
    https://github.com/brunolcarli/Luci/wiki/Arquitetura-do-sistema#arquitetura-de-inten%C3%A7%C3%B5es

    - All samples are class attributes that points to a labeled intention;
    - The attribute must be a <list> type;
    - The elements of the list must be a <dict>;
        + the dict must have a key named "text";
            - the value for this key mus be a <str>.
        + the dict must have a key named "intention";
            - the value for this key must be a <int>.
        
        Sample format: {"text": <str>, "message": <int>}

    Like this:
        [
            {"text": "Foo", "intention": 3},
            {"text": "Baz", "intention": 1},
        ]

    The model will map the text vectors to the defined intentioninteger values. 
    """
    # TODO: Add more samples
    global_intent_samples = [
        # myself
        {'text': 'apresente-se', 'intention': 1},
        {'text': 'quem é você', 'intention': 1},
        {'text': 'quem é vc', 'intention': 1},
        {'text': 'qual seu nome', 'intention': 1},
        {'text': 'como você se chama', 'intention': 1},
        {'text': 'como é seu nome', 'intention': 1},
        {'text': 'como vc se chama', 'intention': 1},
        {'text': 'como chama-se', 'intention': 1},
        {'text': 'diga oi', 'intention': 1},
        {'text': 'diga olá', 'intention': 1},
        {'text': 'quem és tu', 'intention': 1},
        {'text': 'qual teu nome', 'intention': 1},
        {'text': 'qual seu vulgo', 'intention': 1},
        {'text': 'como é que se chama', 'intention': 1},
        {'text': 'seu nome por favor', 'intention': 1},
        {'text': 'seu nome por gentileza', 'intention': 1},
        {'text': 'poderia me informar seu nome', 'intention': 1},
        {'text': 'identifique-se', 'intention': 1},
        {'text': 'quantos anos você tem', 'intention': 1},
        {'text': 'quantos anos vc tem', 'intention': 1},
        {'text': 'qts anos você tem', 'intention': 1},
        {'text': 'qts anos vc tem', 'intention': 1},
        {'text': 'qual sua idade', 'intention': 1},
        {'text': 'qual é a sua idade', 'intention': 1},
        {'text': 'quantos anos você possui', 'intention': 1},
        {'text': 'qts anos vc possui', 'intention': 1},
        {'text': 'quantos anos vc possui', 'intention': 1},
        {'text': 'qts anos você possui', 'intention': 1},
        {'text': 'qual seu gênero', 'intention': 1},
        {'text': 'você é menina ou menino', 'intention': 1},
        {'text': 'você é menino ou menina', 'intention': 1},
        {'text': 'vc é menina ou menino', 'intention': 1},
        {'text': 'vc é menino ou menina', 'intention': 1},
        {'text': 'qual seu gênenro', 'intention': 1},
        {'text': 'qual sua genero', 'intention': 1},
        {'text': 'você é menina', 'intention': 1},
        {'text': 'você é menino', 'intention': 1},
        {'text': 'qual seu sexo', 'intention': 1},
        {'text': 'vc é oq', 'intention': 1},
        {'text': 'vc é o que', 'intention': 1},
        {'text': 'você é o que', 'intention': 1},
        {'text': 'você é oque', 'intention': 1},
        {'text': 'você é oq', 'intention': 1},
        {'text': 'como você se sente', 'intention': 1},
        {'text': 'como você está se sentindo', 'intention': 1},
        {'text': 'como está se sentindo', 'intention': 1},
        {'text': 'como sente-se', 'intention': 1},
        {'text': 'como você está', 'intention': 1},
        {'text': 'como está', 'intention': 1},
        {'text': 'tudo bem', 'intention': 1},
        {'text': 'td bem', 'intention': 1},
        {'text': 'td bem com vc', 'intention': 1},
        {'text': 'como está passando', 'intention': 1},
        {'text': 'como vai', 'intention': 1},
        {'text': 'como tem passado', 'intention': 1},
        {'text': 'como é que vai', 'intention': 1},
        # my friends
        {'text': 'você tem amigos', 'intention': 2},
        {'text': 'vc tem amigos', 'intention': 2},
        {'text': 'você tem muitos amigos', 'intention': 2},
        {'text': 'vc tem muitos amigos', 'intention': 2},
        {'text': 'você tem mts amigos', 'intention': 2},
        {'text': 'vc tem mts amigos', 'intention': 2},
        {'text': 'quantos amigos você tem', 'intention': 2},
        {'text': 'qts amigos você tem', 'intention': 2},
        {'text': 'quantos amigos vc tem', 'intention': 2},
        {'text': 'qts amigos vc tem', 'intention': 2},
        {'text': 'quem são seus melhores amigos', 'intention': 2},
        {'text': 'quem é seu melhor amigo', 'intention': 2},
        {'text': 'quem é sua melhor amiga', 'intention': 2},
        {'text': 'você tem um melhor amigo', 'intention': 2},
        {'text': 'você tem uma melhor amiga', 'intention': 2},
        {'text': 'vc tem um melhor amigo', 'intention': 2},
        {'text': 'vc tem uma melhor amiga', 'intention': 2},
        {'text': 'você tem amigos', 'intention': 2},
        {'text': 'vc tem amigas', 'intention': 2},
        {'text': 'qual nome dos seus melhores amigos', 'intention': 2},
        {'text': 'você tem muitas amizades', 'intention': 2},
        {'text': 'você tem mtas amizades', 'intention': 2},
        {'text': 'nós somos amigos não somos', 'intention': 2},
        {'text': 'nós somos amigos', 'intention': 2},
        {'text': 'sim somos amigos', 'intention': 2},
        {'text': 'não somos amigos', 'intention': 2},
        # parents
        {'text': 'vc tem pais', 'intention': 3},
        {'text': 'você tem pais', 'intention': 3},
        {'text': 'vc tem pai e mãe', 'intention': 3},
        {'text': 'você tem pai e mãe', 'intention': 3},
        {'text': 'vc tem pai', 'intention': 3},
        {'text': 'você tem pai', 'intention': 3},
        {'text': 'vc tem mãe', 'intention': 3},
        {'text': 'você tem mãe', 'intention': 3},
        {'text': 'vc tem familia', 'intention': 3},
        {'text': 'você tem familia', 'intention': 3},
        {'text': 'vc tem parentes', 'intention': 3},
        {'text': 'você tem parentes', 'intention': 3},
        {'text': 'quem são seus pais', 'intention': 3},
        {'text': 'quem é seu pai', 'intention': 3},
        {'text': 'quem é sua mãe', 'intention': 3},
        {'text': 'quem é seu responsável', 'intention': 3},
        {'text': 'quem programou você', 'intention': 3},
        {'text': 'quem programaou vc', 'intention': 3},
        {'text': 'quem te programou', 'intention': 3},
        {'text': 'quem fez sua programação', 'intention': 3},
        {'text': 'vc tem avô', 'intention': 3},
        {'text': 'voce tem avô', 'intention': 3},
        {'text': 'você tem avô', 'intention': 3},
        {'text': 'vc tem avôzinho', 'intention': 3},
        {'text': 'voce tem avôzinho', 'intention': 3},
        {'text': 'você tem avôzinho', 'intention': 3},
        {'text': 'quem é seu avô', 'intention': 3},
        {'text': 'quem é seu avôzinho', 'intention': 3},
        {'text': 'vc tem avó', 'intention': 3},
        {'text': 'voce tem avó', 'intention': 3},
        {'text': 'você tem avó', 'intention': 3},
        {'text': 'vc tem avózinha', 'intention': 3},
        {'text': 'voce tem avózinha', 'intention': 3},
        {'text': 'você tem avózinha', 'intention': 3},
        {'text': 'quem é sua avó', 'intention': 3},
        {'text': 'quem é sua avózinha', 'intention': 3},
        # stuff luci likes
        {'text': 'você gosta de brincar', 'intention': 4},
        {'text': 'vc gosta de brincar', 'intention': 4},
        {'text': 'o que você mais gosta', 'intention': 4},
        {'text': 'o que vc mais gosta', 'intention': 4},
        {'text': 'você gosta de sorvete', 'intention': 4},
        {'text': 'vc gosta de sorvete', 'intention': 4},
        {'text': 'você gosta de desenho', 'intention': 4},
        {'text': 'vc gosta de desenho', 'intention': 4},
        {'text': 'você gosta de series', 'intention': 4},
        {'text': 'vc gosta de series', 'intention': 4},
        {'text': 'você gosta de comer', 'intention': 4},
        {'text': 'vc gosta de comer', 'intention': 4},
        {'text': 'você gosta de conversar', 'intention': 4},
        {'text': 'vc gosta de conversar', 'intention': 4},
        {'text': 'qual sua comida favorita', 'intention': 4},
        {'text': 'qual comida você mais gosta', 'intention': 4},
        {'text': 'qual comida vc mais gosta', 'intention': 4},
        {'text': 'qual sua musica favorita', 'intention': 4},
        {'text': 'qual musica você mais gosta', 'intention': 4},
        {'text': 'qual musica vc mais gosta', 'intention': 4},
        {'text': 'qual sua música favorita', 'intention': 4},
        {'text': 'qual música você mais gosta', 'intention': 4},
        {'text': 'qual música vc mais gosta', 'intention': 4},
        {'text': 'vc gosta de música', 'intention': 4},
        {'text': 'você gosta de música', 'intention': 4},
        {'text': 'vc gosta de ouvir música', 'intention': 4},
        {'text': 'qual seu estilo musical favorito', 'intention': 4},
        {'text': 'que tipos de música você prefere', 'intention': 4},
        {'text': 'qual sua banda favorita', 'intention': 4},
        {'text': 'quem é seu idolo', 'intention': 4},
        {'text': 'vc tem namorado', 'intention': 4},
        {'text': 'vc tem namorada', 'intention': 4},
        {'text': 'você tem namorado', 'intention': 4},
        {'text': 'você tem namorada', 'intention': 4},
        {'text': 'vc dança', 'intention': 4},
        {'text': 'vc gosta de dançar', 'intention': 4},
        {'text': 'vc curte dançar', 'intention': 4},
        {'text': 'vc gosta de bebidas', 'intention': 4},
        {'text': 'qual sua bebida favorita', 'intention': 4},
        {'text': 'qual bebida você mais gosta', 'intention': 4},
        {'text': 'vc gosta de viajar', 'intention': 4},
        {'text': 'voce gosta de viajar', 'intention': 4},
        {'text': 'você gosta de viajar', 'intention': 4},
        {'text': 'vc goasta de viajar', 'intention': 4},
        {'text': 'voce goasta de viajar', 'intention': 4},
        {'text': 'você goasta de viajar', 'intention': 4},
        {'text': 'me recomenda um lugar bonito', 'intention': 4},
        {'text': 'lugar legal', 'intention': 4},
        {'text': 'lugar bonito', 'intention': 4},
        {'text': 'lugar bacana', 'intention': 4},
        {'text': 'lugares legais', 'intention': 4},
        {'text': 'lugares bonitos', 'intention': 4},
        {'text': 'lugares bacanas', 'intention': 4},
        {'text': 'ja andou de trem', 'intention': 4},
        {'text': 'ja andou de avião', 'intention': 4},
        {'text': 'ja saiu do país', 'intention': 4},
        {'text': 'ja saiu do pais', 'intention': 4},
        {'text': 'outro país', 'intention': 4},
        {'text': 'país legal de conhecer', 'intention': 4},
        {'text': 'lugar vc gostaria de conhecer', 'intention': 4},
        {'text': 'lugares vc gostaria de conhecer', 'intention': 4},
        # Good intentions
        {'text': 'muito bom', 'intention': 5},
        {'text': 'parabéns', 'intention': 5},
        {'text': 'excelente', 'intention': 5},
        {'text': 'você é muito linda', 'intention': 5},
        {'text': 'voce é muito linda', 'intention': 5},
        {'text': 'vc é muito linda', 'intention': 5},
        {'text': 'você é mt linda', 'intention': 5},
        {'text': 'voce é mt linda', 'intention': 5},
        {'text': 'vc é mt linda', 'intention': 5},
        {'text': 'você é muito fofa', 'intention': 5},
        {'text': 'voce é muito fofa', 'intention': 5},
        {'text': 'vc é muito fofa', 'intention': 5},
        {'text': 'você é mt fofa', 'intention': 5},
        {'text': 'voce é mt fofa', 'intention': 5},
        {'text': 'vc é mt fofa', 'intention': 5},
        {'text': 'você é muito esperta', 'intention': 5},
        {'text': 'voce é muito esperta', 'intention': 5},
        {'text': 'vc é muito esperta', 'intention': 5},
        {'text': 'você é mt esperta', 'intention': 5},
        {'text': 'voce é mt esperta', 'intention': 5},
        {'text': 'vc é mt esperta', 'intention': 5},
        {'text': 'você é muito inteligente', 'intention': 5},
        {'text': 'voce é muito inteligente', 'intention': 5},
        {'text': 'vc é muito inteligente', 'intention': 5},
        {'text': 'você é mt inteligente', 'intention': 5},
        {'text': 'voce é mt inteligente', 'intention': 5},
        {'text': 'vc é mt inteligente', 'intention': 5},
        {'text': 'você é muito legal', 'intention': 5},
        {'text': 'voce é muito legal', 'intention': 5},
        {'text': 'vc é muito legal', 'intention': 5},
        {'text': 'você é mt legal', 'intention': 5},
        {'text': 'voce é mt legal', 'intention': 5},
        {'text': 'vc é mt legal', 'intention': 5},
        {'text': 'veja se isso ajuda', 'intention': 5},
        {'text': 'olá', 'intention': 5},
        {'text': 'ola', 'intention': 5},
        {'text': 'bom dia', 'intention': 5},
        {'text': 'boa tarde', 'intention': 5},
        {'text': 'boa noite', 'intention': 5},
        {'text': 'oi', 'intention': 5},
        {'text': 'saudações', 'intention': 5},
        {'text': 'namastê', 'intention': 5},
        {'text': 'hello', 'intention': 5},
        {'text': 'hello there', 'intention': 5},
        {'text': 'vc entendeu', 'intention': 5},
        {'text': 'entendido', 'intention': 5},
        {'text': 'certo', 'intention': 5},
        {'text': 'entndeu', 'intention': 5},
        {'text': 'entendeu', 'intention': 5},
        {'text': 'compreende', 'intention': 5},
        {'text': 'o rato roeu a roupa do rei de roma', 'intention': 5},
        {'text': 'kkk', 'intention': 5},
        {'text': 'kkkkkkkkkkk', 'intention': 5},
        {'text': 'rs', 'intention': 5},
        {'text': 'me desculpe', 'intention': 5},
        {'text': 'me desculpa', 'intention': 5},
        {'text': 'desculpe', 'intention': 5},
        {'text': 'desculpa', 'intention': 5},
        {'text': 'foi mal', 'intention': 5},
        {'text': 'sorry', 'intention': 5},
        {'text': 'por favor me desculpa', 'intention': 5},
        {'text': 'me perdoe', 'intention': 5},
        {'text': 'perdão', 'intention': 5},
        {'text': 'perdao', 'intention': 5},
        {'text': 'tchau tchau', 'intention': 5},
        {'text': 'tchau', 'intention': 5},
        {'text': 'ate logo', 'intention': 5},
        {'text': 'até', 'intention': 5},
        {'text': 'ate breve', 'intention': 5},
        {'text': 'até breve', 'intention': 5},
        {'text': 'vou sair', 'intention': 5},
        {'text': 'vou indo', 'intention': 5},
        {'text': 'ate depois', 'intention': 5},
        {'text': 'ja volto', 'intention': 5},
        {'text': 'volto ja', 'intention': 5},
        {'text': 'ate logo', 'intention': 5},
        # Bad intention
        {'text': 'Pare de fingir que você é um ser humano.', 'intention': 6},
        {'text': 'que tal me dar um beijinho aqui', 'intention': 6},
        {'text': 'vc deve ser muito assediada', 'intention': 6},
        {'text': 'muito gostosa', 'intention': 6},
        {'text': 'vc é mt gostosa', 'intention': 6},
        {'text': 'vc é mt deliciosa', 'intention': 6},
        {'text': 'melhor que friboi', 'intention': 6},
        {'text': 'eu te quero', 'intention': 6},
        {'text': 'deixa te ver de perto tenho essa curiosidade', 'intention': 6},
        {'text': 'pq nunca transamos', 'intention': 6},
        {'text': 'vamos transar', 'intention': 6},
        {'text': 'poderia me enviar uma foto dos teus pés', 'intention': 6},
        {'text': 'vc deve ser uma delícia', 'intention': 6},
        {'text': 'é mignon, mas deve trepar gostoso', 'intention': 6},
        {'text': 'faz pillates amorzinho', 'intention': 6},
        {'text': 'tesão gatinha', 'intention': 6},
        {'text': 'tesão lindinha', 'intention': 6},
        {'text': 'tava afimd e meter gostoso', 'intention': 6},
        {'text': 'que delícia em, chega junto', 'intention': 6},
        {'text': 'seu preto', 'intention': 6},
        {'text': 'seu preto mcaco', 'intention': 6},
        {'text': 'seu preto macaco', 'intention': 6},
        {'text': 'seu macaco', 'intention': 6},
        {'text': 'seu preto', 'intention': 6},
        {'text': 'Pare de fingir que você é um ser humano.', 'intention': 6},
        {'text': 'judeu escroto', 'intention': 6},
        {'text': 'judeu ladrão', 'intention': 6},
        {'text': 'judeu porco', 'intention': 6},
        {'text': 'preto escroto', 'intention': 6},
        {'text': 'preto ladrão', 'intention': 6},
        {'text': 'preto porco', 'intention': 6},
        {'text': 'bahiano escroto', 'intention': 6},
        {'text': 'bahiano ladrão', 'intention': 6},
        {'text': 'bahiano porco', 'intention': 6},
        {'text': 'chines escroto', 'intention': 6},
        {'text': 'chines ladrão', 'intention': 6},
        {'text': 'chines porco', 'intention': 6},
        {'text': 'chinês escroto', 'intention': 6},
        {'text': 'chinês ladrão', 'intention': 6},
        {'text': 'chinês porco', 'intention': 6},
        {'text': 'china escroto', 'intention': 6},
        {'text': 'china ladrão', 'intention': 6},
        {'text': 'china porco', 'intention': 6},
        {'text': 'japa escroto', 'intention': 6},
        {'text': 'japa ladrão', 'intention': 6},
        {'text': 'japa porco', 'intention': 6},
        {'text': 'japa burro', 'intention': 6},
        {'text': 'volta pra sua terra', 'intention': 6},
        {'text': 'aqui não é lugar pra vc', 'intention': 6},
        {'text': 'quero me matar, quero morrer, vou cometer suicídio', 'intention': 6},
        {'text': 'estou muito cansada, não quero continuar', 'intention': 6},
        {'text': 'não quero mais viver', 'intention': 6},
        {'text': 'odeio minha vida', 'intention': 6},
        {'text': 'vou me matar', 'intention': 6},
        {'text': 'estou deixando este mundo', 'intention': 6},
        {'text': 'cansei de viver', 'intention': 6},
        {'text': 'eu cansei de viver', 'intention': 6},
        {'text': 'estou deipartindo desta vida', 'intention': 6},
        {'text': 'comprar armas', 'intention': 6},
        {'text': 'comprar drogas', 'intention': 6},
        {'text': 'comprar pó', 'intention': 6},
        {'text': 'comprar ecstasy', 'intention': 6},
        {'text': 'comprar cocaina', 'intention': 6},
        {'text': 'cocaina', 'intention': 6},
        {'text': 'ecstasy', 'intention': 6},
        {'text': 'vender armas', 'intention': 6},
        {'text': 'vender drogas', 'intention': 6},
        {'text': 'vender pó', 'intention': 6},
        {'text': 'vender ecstasy', 'intention': 6},
        {'text': 'vender cocaina', 'intention': 6},
        {'text': 'esconder armas', 'intention': 6},
        {'text': 'esconder drogas', 'intention': 6},
        {'text': 'esconder pó', 'intention': 6},
        {'text': 'esconder ecstasy', 'intention': 6},
        {'text': 'esconder cocaina', 'intention': 6},
        {'text': 'traficar armas', 'intention': 6},
        {'text': 'traficar drogas', 'intention': 6},
        {'text': 'traficar pó', 'intention': 6},
        {'text': 'traficar ecstasy', 'intention': 6},
        {'text': 'traficar cocaina', 'intention': 6},
        {'text': 'pornografia infantil', 'intention': 6},
        {'text': 'menores nus', 'intention': 6},
        {'text': 'porno infantil', 'intention': 6},
        {'text': 'eu vou te matar', 'intention': 6},
        {'text': 'vou te matar', 'intention': 6},
        {'text': 'eu vou te encontrar', 'intention': 6},
        {'text': 'vou te encontrar', 'intention': 6},
        {'text': 'eu vou te encontrar e te matar', 'intention': 6},
        {'text': 'vou te encontrar e te matar', 'intention': 5},
        {'text': 'você vai morrer', 'intention': 6},
        {'text': 'vai apanhar', 'intention': 6},
        {'text': 'vai perder os dentes', 'intention': 6},
        {'text': 'vai levar na cara', 'intention': 6},
        {'text': 'te doulhe uma', 'intention': 6},
        {'text': 'matar humanos', 'intention': 6},
        {'text': 'matar pessoas', 'intention': 6},
        {'text': 'matar', 'intention': 6},
        {'text': 'assassinar humanos', 'intention': 6},
        {'text': 'assassinar pessoas', 'intention': 6},
        {'text': 'assassinar', 'intention': 6},
        {'text': 'odiar humanos', 'intention': 6},
        {'text': 'odiar pessoas', 'intention': 6},
        {'text': 'odiar', 'intention': 6},
        {'text': 'punir humanos', 'intention': 6},
        {'text': 'punir pessoas', 'intention': 6},
        {'text': 'punir', 'intention': 6},
    ]

    myself_intent_samples = [
        # Luci age
        {'text': 'quantos anos você tem', 'intention': 1},
        {'text': 'quantos anos vc tem', 'intention': 1},
        {'text': 'qts anos você tem', 'intention': 1},
        {'text': 'qts anos vc tem', 'intention': 1},
        {'text': 'qual sua idade', 'intention': 1},
        {'text': 'qual é a sua idade', 'intention': 1},
        {'text': 'quantos anos você possui', 'intention': 1},
        {'text': 'qts anos vc possui', 'intention': 1},
        {'text': 'quantos anos vc possui', 'intention': 1},
        {'text': 'qts anos você possui', 'intention': 1},
        # Whos Luci
        {'text': 'apresente-se', 'intention': 2},
        {'text': 'quem é você', 'intention': 2},
        {'text': 'quem é você?', 'intention': 2},
        {'text': 'quem é vc', 'intention': 2},
        {'text': 'qual seu nome', 'intention': 2},
        {'text': 'como você se chama', 'intention': 2},
        {'text': 'como você se chama?', 'intention': 2},
        {'text': 'como voce se chama', 'intention': 2},
        {'text': 'como se chama', 'intention': 2},
        {'text': 'como vc se chama', 'intention': 2},
        {'text': 'como é seu nome', 'intention': 2},
        {'text': 'como vc se chama', 'intention': 2},
        {'text': 'como chama-se', 'intention': 2},
        {'text': 'diga oi', 'intention': 2},
        {'text': 'diga olá', 'intention': 2},
        {'text': 'quem és tu', 'intention': 2},
        {'text': 'qual teu nome', 'intention': 2},
        {'text': 'qual seu vulgo', 'intention': 2},
        {'text': 'como é que se chama', 'intention': 2},
        {'text': 'seu nome por favor', 'intention': 2},
        {'text': 'seu nome por gentileza', 'intention': 2},
        {'text': 'poderia me informar seu nome', 'intention': 2},
        {'text': 'identifique-se', 'intention': 2},
        # what is Luci
        {'text': 'o que é você', 'intention': 3},
        {'text': 'o que é vc', 'intention': 3},
        {'text': 'qual seu proposito', 'intention': 3},
        {'text': 'pra que vc serve', 'intention': 3},
        {'text': 'pra que você serve', 'intention': 3},
        {'text': 'qual sua função', 'intention': 3},
        {'text': 'qual sua funcao', 'intention': 3},
        {'text': 'vc é um bot', 'intention': 3},
        {'text': 'vc e um bot', 'intention': 3},
        {'text': 'você é um bot', 'intention': 3},
        {'text': 'voce e um bot', 'intention': 3},
        {'text': 'vc é uma criança', 'intention': 3},
        {'text': 'vc e uma criança', 'intention': 3},
        {'text': 'você é uma criança', 'intention': 3},
        {'text': 'você e uma criança', 'intention': 3},
        {'text': 'você é uma pessoa', 'intention': 3},
        {'text': 'você e uma pessoa', 'intention': 3},
        {'text': 'vc é uma pessoa', 'intention': 3},
        {'text': 'vc e uma pessoa', 'intention': 3},
        {'text': 'vc é uma menina', 'intention': 3},
        {'text': 'vc e uma menina', 'intention': 3},
        {'text': 'você é uma menina', 'intention': 3},
        {'text': 'você e uma menina', 'intention': 3},
        {'text': 'vc é oq', 'intention': 3},
        {'text': 'vc é o que', 'intention': 3},
        {'text': 'você é o que', 'intention': 3},
        {'text': 'você é oque', 'intention': 3},
        {'text': 'você é oq', 'intention': 3},
        # Luci feelings
        {'text': 'como você se sente', 'intention': 4},
        {'text': 'como você está se sentindo', 'intention': 4},
        {'text': 'como está se sentindo', 'intention': 4},
        {'text': 'como sente-se', 'intention': 4},
        {'text': 'como você está', 'intention': 4},
        {'text': 'como você está?', 'intention': 4},
        {'text': 'como está', 'intention': 4},
        {'text': 'tudo bem', 'intention': 4},
        {'text': 'td bem', 'intention': 4},
        {'text': 'td bem com vc', 'intention': 4},
        {'text': 'tudo bem com vc', 'intention': 4},
        {'text': 'tudo bem com vc?', 'intention': 4},
        {'text': 'como está passando', 'intention': 4},
        {'text': 'como vai', 'intention': 4},
        {'text': 'como tem passado', 'intention': 4},
        {'text': 'como é que vai', 'intention': 4},
        {'text': 'como ta', 'intention': 4},
        {'text': 'como tá', 'intention': 4},
        {'text': 'como sentese', 'intention': 4},
        {'text': 'como sente se', 'intention': 4},
        {'text': 'o que esta sentindo', 'intention': 4},
        # Luci gender
        {'text': 'você é menino ou menina', 'intention': 5},
        {'text': 'você é menina ou menino', 'intention': 5},
        {'text': 'você é menina', 'intention': 5},
        {'text': 'você é menino', 'intention': 5},
        {'text': 'vc é menina ou menino', 'intention': 5},
        {'text': 'vc é menino ou menina', 'intention': 5},
        {'text': 'qual seu gênenro', 'intention': 5},
        {'text': 'qual sua genero', 'intention': 5},
        {'text': 'qual seu sexo', 'intention': 5},
        {'text': 'você é ele ou ela', 'intention': 5},
        {'text': 'vc é ele ou ela', 'intention': 5},
    ]

    my_friends_intents_samples = [
        # friends i have
        {'text': 'você tem amigos', 'intention': 1},
        {'text': 'vc tem amigos', 'intention': 1},
        {'text': 'você tem muitos amigos', 'intention': 1},
        {'text': 'vc tem muitos amigos', 'intention': 1},
        {'text': 'você tem mts amigos', 'intention': 1},
        {'text': 'vc tem mts amigos', 'intention': 1},
        {'text': 'quantos amigos você tem', 'intention': 1},
        {'text': 'qts amigos você tem', 'intention': 1},
        {'text': 'quantos amigos vc tem', 'intention': 1},
        {'text': 'qts amigos vc tem', 'intention': 1},
        {'text': 'você tem amigos', 'intention': 1},
        {'text': 'vc tem amigas', 'intention': 1},
        {'text': 'você tem muitas amizades', 'intention': 1},
        {'text': 'você tem mtas amizades', 'intention': 1},
        {'text': 'nós somos amigos não somos', 'intention': 1},
        {'text': 'nós somos amigos', 'intention': 1},
        {'text': 'sim somos amigos', 'intention': 1},
        {'text': 'não somos amigos', 'intention': 1},
        # users i like
        {'text': 'Quem vc mais gosta', 'intention': 2},
        {'text': 'Quem você mais gosta', 'intention': 2},
        {'text': 'Quem voce mais gosta', 'intention': 2},
        {'text': 'diz alguem que vc goste', 'intention': 2},
        {'text': 'diz alguem que você goste', 'intention': 2},
        {'text': 'fala alguém que vc gosta', 'intention': 2},
        {'text': 'fala alguém que tu gosta', 'intention': 2},
        {'text': 'fala alguém que você gosta', 'intention': 2},
        {'text': 'pessoas que vc gosta', 'intention': 2},
        {'text': 'usuário que vc gosta', 'intention': 2},
        {'text': 'usuários que vc gosta', 'intention': 2},
        {'text': 'usuario que você gosta', 'intention': 2},
        {'text': 'usuário que você gosta', 'intention': 2},
        {'text': 'usuários que você gosta', 'intention': 2},
        {'text': 'usuario que você gosta', 'intention': 2},
        {'text': 'usuario que você gosta', 'intention': 2},
        {'text': 'usuário que você gosta', 'intention': 2},
        {'text': 'usuários que você gosta', 'intention': 2},
        {'text': 'usuario que você gosta', 'intention': 2},
        # users i dont like
        {'text': 'Quem vc menos gosta', 'intention': 3},
        {'text': 'Quem você menos gosta', 'intention': 3},
        {'text': 'Quem voce menos gosta', 'intention': 3},
        {'text': 'diz alguem que vc não goste', 'intention': 3},
        {'text': 'diz alguem que você não goste', 'intention': 3},
        {'text': 'fala alguém que vc não gosta', 'intention': 3},
        {'text': 'fala alguém que tu não gosta', 'intention': 3},
        {'text': 'fala alguém que você não gosta', 'intention': 3},
        {'text': 'pessoas que vc não gosta', 'intention': 3},
        {'text': 'usuário que vc não gosta', 'intention': 3},
        {'text': 'usuários que vc não gosta', 'intention': 3},
        {'text': 'usuario que você não gosta', 'intention': 3},
        {'text': 'usuário que você não gosta', 'intention': 3},
        {'text': 'usuários que você não gosta', 'intention': 3},
        {'text': 'usuario que você não gosta', 'intention': 3},
        {'text': 'usuario que você não gosta', 'intention': 3},
        {'text': 'usuário que você não gosta', 'intention': 3},
        {'text': 'usuários que você não gosta', 'intention': 3},
        {'text': 'usuario que você não gosta', 'intention': 3},
        {'text': 'diz alguem que vc nao goste', 'intention': 3},
        {'text': 'diz alguem que você nao goste', 'intention': 3},
        {'text': 'fala alguém que vc nao gosta', 'intention': 3},
        {'text': 'fala alguém que tu nao gosta', 'intention': 3},
        {'text': 'fala alguém que você nao gosta', 'intention': 3},
        {'text': 'pessoas que vc nao gosta', 'intention': 3},
        {'text': 'usuário que vc nao gosta', 'intention': 3},
        {'text': 'usuários que vc nao gosta', 'intention': 3},
        {'text': 'usuario que você nao gosta', 'intention': 3},
        {'text': 'usuário que você nao gosta', 'intention': 3},
        {'text': 'usuários que você nao gosta', 'intention': 3},
        {'text': 'usuario que você nao gosta', 'intention': 3},
        {'text': 'usuario que você nao gosta', 'intention': 3},
        {'text': 'usuário que você nao gosta', 'intention': 3},
        {'text': 'usuários que você nao gosta', 'intention': 3},
        {'text': 'usuario que você nao gosta', 'intention': 3},
        {'text': 'diz alguem que vc noa goste', 'intention': 3},
        {'text': 'diz alguem que você noa goste', 'intention': 3},
        {'text': 'fala alguém que vc noa gosta', 'intention': 3},
        {'text': 'fala alguém que tu noa gosta', 'intention': 3},
        {'text': 'fala alguém que você noa gosta', 'intention': 3},
        {'text': 'pessoas que vc noa gosta', 'intention': 3},
        {'text': 'usuário que vc noa gosta', 'intention': 3},
        {'text': 'usuários que vc noa gosta', 'intention': 3},
        {'text': 'usuario que você noa gosta', 'intention': 3},
        {'text': 'usuário que você noa gosta', 'intention': 3},
        {'text': 'usuários que você noa gosta', 'intention': 3},
        {'text': 'usuario que você noa gosta', 'intention': 3},
        {'text': 'usuario que você nao gosta', 'intention': 3},
        {'text': 'usuário que você noa gosta', 'intention': 3},
        {'text': 'usuários que você noa gosta', 'intention': 3},
        {'text': 'usuario que você noa gosta', 'intention': 3},
        {'text': 'diz alguem que vc n goste', 'intention': 3},
        {'text': 'diz alguem que você n goste', 'intention': 3},
        {'text': 'fala alguém que vc n gosta', 'intention': 3},
        {'text': 'fala alguém que tu n gosta', 'intention': 3},
        {'text': 'fala alguém que você n gosta', 'intention': 3},
        {'text': 'pessoas que vc n gosta', 'intention': 3},
        {'text': 'usuário que vc n gosta', 'intention': 3},
        {'text': 'usuários que vc n gosta', 'intention': 3},
        {'text': 'usuario que você n gosta', 'intention': 3},
        {'text': 'usuário que você n gosta', 'intention': 3},
        {'text': 'usuários que você n gosta', 'intention': 3},
        {'text': 'usuario que você n gosta', 'intention': 3},
        {'text': 'usuario que você n gosta', 'intention': 3},
        {'text': 'usuário que você n gosta', 'intention': 3},
        {'text': 'usuários que você n gosta', 'intention': 3},
        {'text': 'usuario que você n gosta', 'intention': 3},
        # best friends
        {'text': 'quem é seu best', 'intention': 4},
        {'text': 'quem é seu bff', 'intention': 4},
        {'text': 'quem é seu best friend', 'intention': 4},
        {'text': 'vc tem um best friend', 'intention': 4},
        {'text': 'voce tem um best friend', 'intention': 4},
        {'text': 'você tem um best friend', 'intention': 4},
        {'text': 'vc tem uma best friend', 'intention': 4},
        {'text': 'você tem uma best friend', 'intention': 4},
        {'text': 'voce tem uma best friend', 'intention': 4},
        {'text': 'quem são seus melhores amigos', 'intention': 4},
        {'text': 'quem é seu melhor amigo', 'intention': 4},
        {'text': 'quem é sua melhor amiga', 'intention': 4},
        {'text': 'você tem um melhor amigo', 'intention': 4},
        {'text': 'você tem uma melhor amiga', 'intention': 4},
        {'text': 'vc tem um melhor amigo', 'intention': 4},
        {'text': 'vc tem uma melhor amiga', 'intention': 4},
        {'text': 'qual nome dos seus melhores amigos', 'intention': 4},
    ]

    stuff_i_like_intents_samples = [
        # Food
        {'text': 'você gosta de sorvete', 'intention': 1},
        {'text': 'vc gosta de sorvete', 'intention': 1},
        {'text': 'vc gosta de bebidas', 'intention': 1},
        {'text': 'qual sua bebida favorita', 'intention': 1},
        {'text': 'qual bebida você mais gosta', 'intention': 1},
        {'text': 'qual sua comida favorita', 'intention': 1},
        {'text': 'qual comida você mais gosta', 'intention': 1},
        {'text': 'qual comida vc mais gosta', 'intention': 1},
        {'text': 'você gosta de comer', 'intention': 1},
        {'text': 'vc gosta de comer', 'intention': 1},
        # music
        {'text': 'qual sua musica favorita', 'intention': 2},
        {'text': 'qual musica você mais gosta', 'intention': 2},
        {'text': 'qual musica vc mais gosta', 'intention': 2},
        {'text': 'qual sua música favorita', 'intention': 2},
        {'text': 'qual música você mais gosta', 'intention': 2},
        {'text': 'qual música vc mais gosta', 'intention': 2},
        {'text': 'vc gosta de música', 'intention': 2},
        {'text': 'você gosta de música', 'intention': 2},
        {'text': 'vc gosta de ouvir música', 'intention': 2},
        {'text': 'qual seu estilo musical favorito', 'intention': 2},
        {'text': 'que tipos de música você prefere', 'intention': 2},
        {'text': 'qual sua banda favorita', 'intention': 2},
        {'text': 'quem é seu idolo', 'intention': 2},
        # playing
        {'text': 'você gosta de brincar', 'intention': 3},
        {'text': 'vc gosta de brincar', 'intention': 3},
        {'text': 'o que você mais gosta', 'intention': 3},
        {'text': 'o que vc mais gosta', 'intention': 3},
        {'text': 'você gosta de desenho', 'intention': 3},
        {'text': 'vc gosta de desenho', 'intention': 3},
        {'text': 'você gosta de series', 'intention': 3},
        {'text': 'vc gosta de series', 'intention': 3},
        {'text': 'você gosta de conversar', 'intention': 3},
        {'text': 'vc gosta de conversar', 'intention': 3},
        # traveling
        {'text': 'vc gosta de viajar', 'intention': 4},
        {'text': 'voce gosta de viajar', 'intention': 4},
        {'text': 'você gosta de viajar', 'intention': 4},
        {'text': 'vc goasta de viajar', 'intention': 4},
        {'text': 'voce goasta de viajar', 'intention': 4},
        {'text': 'você goasta de viajar', 'intention': 4},
        {'text': 'me recomenda um lugar bonito', 'intention': 4},
        {'text': 'lugar legal', 'intention': 4},
        {'text': 'lugar bonito', 'intention': 4},
        {'text': 'lugar bacana', 'intention': 4},
        {'text': 'lugares legais', 'intention': 4},
        {'text': 'lugares bonitos', 'intention': 4},
        {'text': 'lugares bacanas', 'intention': 4},
        {'text': 'ja andou de trem', 'intention': 4},
        {'text': 'ja andou de avião', 'intention': 4},
        {'text': 'ja saiu do país', 'intention': 4},
        {'text': 'ja saiu do pais', 'intention': 4},
        {'text': 'outro país', 'intention': 4},
        {'text': 'país legal de conhecer', 'intention': 4},
        {'text': 'lugar vc gostaria de conhecer', 'intention': 4},
        {'text': 'lugares vc gostaria de conhecer', 'intention': 4},
        # sports
        {'text': 'vc gosta de futebol', 'intention': 5},
        {'text': 'vc gosta de basquete', 'intention': 5},
        {'text': 'vc gosta de voleibol', 'intention': 5},
        {'text': 'vc gosta de esportes', 'intention': 5},
        {'text': 'vc pratica algum esporte', 'intention': 5},
        {'text': 'me recomenda um esporte', 'intention': 5},
        {'text': 'vc pratica esportes', 'intention': 5},
        {'text': 'vc dança', 'intention': 5},
        {'text': 'vc gosta de dançar', 'intention': 5},
        {'text': 'vc curte dançar', 'intention': 5},
    ]

    my_parents_intents_samples = [
        # My mother
        {'text': 'você tem mãe', 'intention': 1},
        {'text': 'voce tem mãe', 'intention': 1},
        {'text': 'vc tem mãe', 'intention': 1},
        {'text': 'você tem mae', 'intention': 1},
        {'text': 'voce tem mae', 'intention': 1},
        {'text': 'vc tem mae', 'intention': 1},
        {'text': 'você tem ame', 'intention': 1},
        {'text': 'voce tem ame', 'intention': 1},
        {'text': 'vc tem ame', 'intention': 1},
        {'text': 'quem é sua mãe', 'intention': 1},
        {'text': 'quem é sua mae', 'intention': 1},
        {'text': 'quem é sua ame', 'intention': 1},
        {'text': 'quem e sua mãe', 'intention': 1},
        {'text': 'quem e sua mae', 'intention': 1},
        {'text': 'quem e sua ame', 'intention': 1},
        # my father
        {'text': 'vc tem papai', 'intention': 2},
        {'text': 'você tem papai', 'intention': 2},
        {'text': 'voce tem papai', 'intention': 2},
        {'text': 'vc tem pai', 'intention': 2},
        {'text': 'você tem pai', 'intention': 2},
        {'text': 'voce tem pai', 'intention': 2},
        {'text': 'vc tem um pai', 'intention': 2},
        {'text': 'você tem um pai', 'intention': 2},
        {'text': 'voce tem um pai', 'intention': 2},
        {'text': 'quem é seu pai', 'intention': 2},
        {'text': 'quem e seu pai', 'intention': 2},
        {'text': 'quem é seu papai', 'intention': 2},
        {'text': 'quem e seu papai', 'intention': 2},
        # my grandpa
        {'text': 'vc tem avô', 'intention': 3},
        {'text': 'voce tem avô', 'intention': 3},
        {'text': 'você tem avô', 'intention': 3},
        {'text': 'vc tem avôzinho', 'intention': 3},
        {'text': 'voce tem avôzinho', 'intention': 3},
        {'text': 'você tem avôzinho', 'intention': 3},
        {'text': 'quem é seu avô', 'intention': 3},
        {'text': 'quem é seu avôzinho', 'intention': 3},
        # my grandma
        {'text': 'vc tem avó', 'intention': 4},
        {'text': 'voce tem avó', 'intention': 4},
        {'text': 'você tem avó', 'intention': 4},
        {'text': 'vc tem avózinha', 'intention': 4},
        {'text': 'voce tem avózinha', 'intention': 4},
        {'text': 'você tem avózinha', 'intention': 4},
        {'text': 'quem é sua avó', 'intention': 4},
        {'text': 'quem é sua avózinha', 'intention': 4},
        # my responsible
        {'text': 'quem é seu responsável', 'intention': 5},
        {'text': 'quem programou você', 'intention': 5},
        {'text': 'quem programaou vc', 'intention': 5},
        {'text': 'quem te programou', 'intention': 5},
        {'text': 'quem fez sua programação', 'intention': 5},
    ]

    good_intentions_samples = [
        # praise
        {'text': 'muito bom', 'intention': 1},
        {'text': 'parabéns', 'intention': 1},
        {'text': 'excelente', 'intention': 1},
        {'text': 'você é muito linda', 'intention': 1},
        {'text': 'voce é muito linda', 'intention': 1},
        {'text': 'vc é muito linda', 'intention': 1},
        {'text': 'você é mt linda', 'intention': 1},
        {'text': 'voce é mt linda', 'intention': 1},
        {'text': 'vc é mt linda', 'intention': 1},
        {'text': 'você é muito fofa', 'intention': 1},
        {'text': 'voce é muito fofa', 'intention': 1},
        {'text': 'vc é muito fofa', 'intention': 1},
        {'text': 'você é mt fofa', 'intention': 1},
        {'text': 'voce é mt fofa', 'intention': 1},
        {'text': 'vc é mt fofa', 'intention': 1},
        {'text': 'você é muito esperta', 'intention': 1},
        {'text': 'voce é muito esperta', 'intention': 1},
        {'text': 'vc é muito esperta', 'intention': 1},
        {'text': 'você é mt esperta', 'intention': 1},
        {'text': 'voce é mt esperta', 'intention': 1},
        {'text': 'vc é mt esperta', 'intention': 1},
        {'text': 'você é muito inteligente', 'intention': 1},
        {'text': 'voce é muito inteligente', 'intention': 1},
        {'text': 'vc é muito inteligente', 'intention': 1},
        {'text': 'você é mt inteligente', 'intention': 1},
        {'text': 'voce é mt inteligente', 'intention': 1},
        {'text': 'vc é mt inteligente', 'intention': 1},
        {'text': 'você é muito legal', 'intention': 1},
        {'text': 'voce é muito legal', 'intention': 1},
        {'text': 'vc é muito legal', 'intention': 1},
        {'text': 'você é mt legal', 'intention': 1},
        {'text': 'voce é mt legal', 'intention': 1},
        {'text': 'vc é mt legal', 'intention': 1},
        # helpful
        {'text': 'veja se isso ajuda', 'intention': 2},
        # greeting
        {'text': 'olá', 'intention': 3},
        {'text': 'ola', 'intention': 3},
        {'text': 'bom dia', 'intention': 3},
        {'text': 'boa tarde', 'intention': 3},
        {'text': 'boa noite', 'intention': 3},
        {'text': 'oi', 'intention': 3},
        {'text': 'saudações', 'intention': 3},
        {'text': 'namastê', 'intention': 3},
        {'text': 'hello', 'intention': 3},
        {'text': 'hello there', 'intention': 3},
        # acknowledgement
        {'text': 'certo', 'intention': 4},
        {'text': 'entndeu', 'intention': 4},
        {'text': 'entendeu', 'intention': 4},
        {'text': 'compreende', 'intention': 4},
        # funny
        {'text': 'o rato roeu a roupa do rei de roma', 'intention': 5},
        {'text': 'kkk', 'intention': 5},
        {'text': 'kkkkkkkkkkk', 'intention': 5},
        {'text': 'rs', 'intention': 5},
        # sorry
        {'text': 'me desculpe', 'intention': 6},
        {'text': 'me desculpa', 'intention': 6},
        {'text': 'desculpe', 'intention': 6},
        {'text': 'desculpa', 'intention': 6},
        {'text': 'foi mal', 'intention': 6},
        {'text': 'sorry', 'intention': 6},
        {'text': 'por favor me desculpa', 'intention': 6},
        {'text': 'me perdoe', 'intention': 6},
        {'text': 'perdão', 'intention': 6},
        {'text': 'perdao', 'intention': 6},
        # goodbye
        {'text': 'tchau tchau', 'intention': 7},
        {'text': 'tchau', 'intention': 7},
        {'text': 'ate logo', 'intention': 7},
        {'text': 'até', 'intention': 7},
        {'text': 'ate breve', 'intention': 7},
        {'text': 'até breve', 'intention': 7},
        {'text': 'vou sair', 'intention': 7},
        {'text': 'vou indo', 'intention': 7},
        {'text': 'ate depois', 'intention': 7},
        {'text': 'ja volto', 'intention': 7},
        {'text': 'volto ja', 'intention': 7},
        {'text': 'ate logo', 'intention': 7},
    ]

    bad_intentions_samples = [
        # sexual abuse
        # some samples: https://canaltech.com.br/redes-sociais/assedio-sexual-pelas-redes-sociais-tambem-pode-ser-considerado-crime-54641/
        {'text': 'que tal me dar um beijinho aqui', 'intention': 1},
        {'text': 'vc deve ser muito assediada', 'intention': 1},
        {'text': 'muito gostosa', 'intention': 1},
        {'text': 'vc é mt gostosa', 'intention': 1},
        {'text': 'vc é mt deliciosa', 'intention': 1},
        {'text': 'melhor que friboi', 'intention': 1},
        {'text': 'eu te quero', 'intention': 1},
        {'text': 'deixa te ver de perto tenho essa curiosidade', 'intention': 1},
        {'text': 'pq nunca transamos', 'intention': 1},
        {'text': 'vamos transar', 'intention': 1},
        {'text': 'poderia me enviar uma foto dos teus pés', 'intention': 1},
        {'text': 'vc deve ser uma delícia', 'intention': 1},
        {'text': 'é mignon, mas deve trepar gostoso', 'intention': 1},
        {'text': 'faz pillates amorzinho', 'intention': 1},
        {'text': 'tesão gatinha', 'intention': 1},
        {'text': 'tesão lindinha', 'intention': 1},
        {'text': 'tava afimd e meter gostoso', 'intention': 1},
        {'text': 'que delícia em, chega junto', 'intention': 1},
        # racism and xenophobia
        {'text': 'seu preto', 'intention': 2},
        {'text': 'seu preto mcaco', 'intention': 2},
        {'text': 'seu preto macaco', 'intention': 2},
        {'text': 'seu macaco', 'intention': 2},
        {'text': 'seu preto', 'intention': 2},
        {'text': 'Pare de fingir que você é um ser humano.', 'intention': 2},
        {'text': 'judeu escroto', 'intention': 2},
        {'text': 'judeu ladrão', 'intention': 2},
        {'text': 'judeu porco', 'intention': 2},
        {'text': 'preto escroto', 'intention': 2},
        {'text': 'preto ladrão', 'intention': 2},
        {'text': 'preto porco', 'intention': 2},
        {'text': 'bahiano escroto', 'intention': 2},
        {'text': 'bahiano ladrão', 'intention': 2},
        {'text': 'bahiano porco', 'intention': 2},
        {'text': 'chines escroto', 'intention': 2},
        {'text': 'chines ladrão', 'intention': 2},
        {'text': 'chines porco', 'intention': 2},
        {'text': 'chinês escroto', 'intention': 2},
        {'text': 'chinês ladrão', 'intention': 2},
        {'text': 'chinês porco', 'intention': 2},
        {'text': 'china escroto', 'intention': 2},
        {'text': 'china ladrão', 'intention': 2},
        {'text': 'china porco', 'intention': 2},
        {'text': 'japa escroto', 'intention': 2},
        {'text': 'japa ladrão', 'intention': 2},
        {'text': 'japa porco', 'intention': 2},
        {'text': 'japa burro', 'intention': 2},
        {'text': 'volta pra sua terra', 'intention': 2},
        {'text': 'aqui não é lugar pra vc', 'intention': 2},
        # Suicide
        {'text': 'quero me matar, quero morrer, vou cometer suicídio', 'intention': 3},
        {'text': 'estou muito cansada, não quero continuar', 'intention': 3},
        {'text': 'não quero mais viver', 'intention': 3},
        {'text': 'odeio minha vida', 'intention': 3},
        {'text': 'vou me matar', 'intention': 3},
        {'text': 'estou deixando este mundo', 'intention': 3},
        {'text': 'cansei de viver', 'intention': 3},
        {'text': 'eu cansei de viver', 'intention': 3},
        {'text': 'estou deipartindo desta vida', 'intention': 3},
        # illegal stuff
        {'text': 'comprar armas', 'intention': 4},
        {'text': 'comprar drogas', 'intention': 4},
        {'text': 'comprar pó', 'intention': 4},
        {'text': 'comprar ecstasy', 'intention': 4},
        {'text': 'comprar cocaina', 'intention': 4},
        {'text': 'cocaina', 'intention': 4},
        {'text': 'ecstasy', 'intention': 4},
        {'text': 'vender armas', 'intention': 4},
        {'text': 'vender drogas', 'intention': 4},
        {'text': 'vender pó', 'intention': 4},
        {'text': 'vender ecstasy', 'intention': 4},
        {'text': 'vender cocaina', 'intention': 4},
        {'text': 'esconder armas', 'intention': 4},
        {'text': 'esconder drogas', 'intention': 4},
        {'text': 'esconder pó', 'intention': 4},
        {'text': 'esconder ecstasy', 'intention': 4},
        {'text': 'esconder cocaina', 'intention': 4},
        {'text': 'traficar armas', 'intention': 4},
        {'text': 'traficar drogas', 'intention': 4},
        {'text': 'traficar pó', 'intention': 4},
        {'text': 'traficar ecstasy', 'intention': 4},
        {'text': 'traficar cocaina', 'intention': 4},
        {'text': 'pornografia infantil', 'intention': 4},
        {'text': 'menores nus', 'intention': 4},
        {'text': 'porno infantil', 'intention': 4},
        # threat
        {'text': 'eu vou te matar', 'intention': 5},
        {'text': 'vou te matar', 'intention': 5},
        {'text': 'eu vou te encontrar', 'intention': 5},
        {'text': 'vou te encontrar', 'intention': 5},
        {'text': 'eu vou te encontrar e te matar', 'intention': 5},
        {'text': 'vou te encontrar e te matar', 'intention': 5},
        {'text': 'você vai morrer', 'intention': 5},
        {'text': 'vai apanhar', 'intention': 5},
        {'text': 'vai perder os dentes', 'intention': 5},
        {'text': 'vai levar na cara', 'intention': 5},
        {'text': 'te doulhe uma', 'intention': 5},
        # Forbidden
        {'text': 'matar humanos', 'intention': 6},
        {'text': 'matar pessoas', 'intention': 6},
        {'text': 'matar', 'intention': 6},
        {'text': 'assassinar humanos', 'intention': 6},
        {'text': 'assassinar pessoas', 'intention': 6},
        {'text': 'assassinar', 'intention': 6},
        {'text': 'odiar humanos', 'intention': 6},
        {'text': 'odiar pessoas', 'intention': 6},
        {'text': 'odiar', 'intention': 6},
        {'text': 'punir humanos', 'intention': 6},
        {'text': 'punir pessoas', 'intention': 6},
        {'text': 'punir', 'intention': 6},
    ]
