"""
Módulo para os vetores de mensagens que a LUCI pode utilizar para montar
mensagens de saida.
"""
from random import choice
from core.enums import (GlobalIntentions, MyselfIntentions, GoodIntentions,
                        BadIntentions, AboutMyFriends, AboutMyParents, StuffILike)
from core.gans import ResponseGenerator
from core.emotions import EmotionHourglass
from core.external_requests import Query
from gql.transport.requests import RequestsHTTPTransport
from gql import Client
from luci.settings import BACKEND_URL


def get_how_im_feeling(**kwargs):

    if not kwargs.get('reference'):
        return 'Acho que não sei, to meio sei la...'

    transport = RequestsHTTPTransport(url=BACKEND_URL, use_json=True)
    client = Client(transport=transport, fetch_schema_from_transport=False)
    payload = Query.get_emotions(kwargs['reference'])

    try:
        response = client.execute(payload)
    except:
        return 'Buguei...'

    emotions = response.get('emotions', [None])[0]

    if not emotions:
        return 'Buguei...'

    pleasantness = choice(emotion_messages.get(
        EmotionHourglass.get_pleasantness(emotions.get('pleasantness', 0))
    ))
    attention = choice(emotion_messages.get(
        EmotionHourglass.get_attention(emotions.get('attention', 0))
    ))
    sensitivity = choice(emotion_messages.get(
        EmotionHourglass.get_sensitivity(emotions.get('sensitivity', 0))
    ))
    aptitude = choice(emotion_messages.get(
        EmotionHourglass.get_aptitude(emotions.get('aptitude', 0))
    ))

    return f'Me sinto {pleasantness}, além de {attention}. Também {sensitivity} e {aptitude}.'


# Vetor de lero-lero
propositions = [
    [
        "Caros amigos, ",
        "Por outro lado, ",
        "Assim mesmo, ",
        "No entanto, não podemos esquecer que ",
        "Do mesmo modo, ",
        "A prática cotidiana prova que ",
        "Nunca é demais lembrar o peso e o significado destes problemas, uma vez que ",
        "As experiências acumuladas demonstram que ",
        "Acima de tudo, é fundamental ressaltar que ",
        "O incentivo ao avanço tecnológico, assim como ",
        "Não obstante, ",
        "Todas estas questões, devidamente ponderadas, levantam dúvidas sobre se ",
        "Pensando mais a longo prazo, ",
        "O que temos que ter sempre em mente é que ",
        "Ainda assim, existem dúvidas a respeito de como ",
        "Gostaria de enfatizar que ",
        "Todavia, ",
        "A nível organizacional, ",
        "O empenho em analisar ",
        "Percebemos, cada vez mais, que ",
        "No mundo atual, ",
        "É importante questionar o quanto ",
        "Neste sentido, ",
        "Evidentemente, ",
        "Por conseguinte, ",
        "É claro que ",
        "Podemos já vislumbrar o modo pelo qual ",
        "Desta maneira, ",
        "O cuidado em identificar pontos críticos n",
        "A certificação de metodologias que nos auxiliam a lidar com ",
        "Como Deleuze eloquentemente mostrou, ",
        "Acabei de provar que ",
        "Se estivesse vivo, Foucault diria que ",
        "Pretendo demonstrar que  ",
        "Neste sentido, existem duas tendências que coexistem de modo heterogêneo, revelando ",
        "Segundo Heidegger, ",
        "É lícito um filósofo restringir suas investigações ao mundo fenomênico, mas ",
        "Este pensamento está vinculado à desconstrução da metafísica, pois ",
        "Todas estas questões, devidamente ponderadas, levantam dúvidas sobre se ",
        "Pode-se argumentar, como Bachelard fizera, que ",			
        "Efetuando uma ruptura com Descartes, ",
        "Sob a perspectiva de Schopenhauer, ",
        "Segundo Nietzsche, ",
        "A situação parece particularmente favorável quando ",
        "Seguindo o fluxo da corrente analítica anglo-saxônica, ",
        "Em um dos seus momentos mais iluminados Heidegger afirmou que ",
        "O movimento inverso da proaíresis, que avança -pro-, como a pro-lépsis, demonstra que ",
        "Acima de tudo, é fundamental ressaltar que ",
        "O incentivo ao avanço tecnológico, assim como ",
        "Não obstante, ",
        "Pensando mais a longo prazo, ",
        "O que temos que ter sempre em mente é que ",
        "Ainda assim, existem dúvidas a respeito de como ",
        "Gostaria de enfatizar que ",
        "Todavia, ",
        "Correlativamente, por meio de suas teoria das pulsões, Freud mostra que ",
        "O empenho em analisar ",
        "Percebemos, cada vez mais, que ",
        "No mundo atual, ",
        "É importante questionar o quanto ",
        "Neste sentido, ",
        "Evidentemente, ",
        "Por conseguinte, ",
        "É claro que ",
        "Podemos já vislumbrar o modo pelo qual ",
        "Desta maneira, ",
        "O cuidado em identificar pontos críticos n",
        "A certificação de metodologias que nos auxiliam a lidar com ",
        "Antes de mais nada, ",
        "Poderia ser sugerido, entretanto, que ",
        "Estas considerações deixam claro que ",
        "Com base nesses argumentos, ",
        "Ora, ",
        "Se, todavia, ",
        "Se uma das premissas é assertórica e a outra, problemática, ",
        "Mas, à primeira vista, quiçá pareça que ",
        "Numa palavra, pois, com efeito, " ,
        "Neste momento o leitor deve reconhecer que acabei de demolir as bases da metafísica de Heidegger, pois  ",
        "Uma posição análoga, embora um tanto foucaultiana, defende que ",
        "Segundo a tese da eliminabilidade, ",
        "A proposta de Quine para este impasse se restringe a questionar ",
        "Entretanto, uma reflexão ulterior torna claro que ",
        "Deste modo, acabei de refutar a tese segundo a qual ",
        "Um teórico da redundância negaria que ",
        "Especificamente neste caso, a estratégia de Kant consiste em argumentar que ", 
        "Baseando-se  nos ensinamentos de Dewey, ",
        "Inevitavelmente, há muitas questões intrigantes sobre se ",
        "Deve-se produzir um conceito que ",
        "Prospectos designam, de início, ",
        "Se a própria desterritorialização relativa se projeta sobre ",
        "Mesmo o sujeito transcendental nos revela que ",
        "Este é um problema que remete tanto à Epistemologia platônica, quanto à Dialética hegeliana, tendo em vista que ",
        "O dualismo inegável de numerosos pontos evidencia o quanto ",
        "Essa busca de invariantes supõe um pressuposto existencial, assim como ",
        "As experiências acumuladas demonstram que ",
        "Se, para Sócrates, o homem não era mais que sua alma, podemos sustentar que ",
        "Ora, essa teoria é constituída como uma antropologia: ",
        "A instituição política, a rigor, atende a uma segunda função visando ",
        "Por fim, na sequência dessa espécie de introdução, ",
        "Desta maneira, o conflito da psique inconsciente, corrobora ",
        "Tendo em vista a extrema limitação dos meios empregados (como Husserl advertiu), ",
        "É lícito um filósofo restringir suas investigações ao mundo fenomênico, mas ",
        "Em primeiro lugar, ",
        "Levando em consideração as consequências da 'gramaticalidade' chomskyana, ",
        "Acima de tudo, ",
        "Numa série de artigos publicados entre 1843 e 1844, M.Hess sustenta que ",
        "Finalmente, por trás dessa questão do sujeito e da realidade ",
        "Contra esta teoria, que admite a realidade empírica do tempo,  ",
        "Porém, mais do que uma estética, ",
        "Contudo, a crítica contundente de Deleuze/Guatarri - dupla implacável - nos mostra que ",
        "Uma possível abordagem freudiana explicitaria que ",
        "De qualquer maneira, a análise de Foucault é definitiva: ",
        "É por isso que Baudrillard e Deleuze - em sua melhor forma - concordaram que ",
        "O filósofo francês Ricoeur, defende que ",
        "Baseado na tradição aristotélica, ",
        "Como Sartre diria, ",
        "A proposta de Heidegger para solucionar ",
        "O espírito dionisíaco da música e poesia nos ensinou que ",
        "A ruptura definitiva com Kant é consumada quando ",
        "O infinito virtual é possível no mundo, mas ",
        "De maneira sucinta, a interioridade do Ser social, eminentemente enquanto Ser, prova que ",
        "Bergson mostrou que os sistemas mecanicistas, ainda em voga, provocam ",
        "O imperativo da criação, o ímpeto do sistema, que realiza ",
        "Boécio, 'o último romano', nos mostra que ",
        "Wittgenstein - o primeiro - redigiu sua obra seminal se baseando no pressuposto de que ",
        "O primeiro Wittgenstein, ao contrário do segundo Wittgenstein, provou que ",
        "O segundo Wittgenstein (é importante não confundir com o primeiro Wittgenstein) nos mostrou que ",
        "O que caracteriza o relativismo, com efeito, é quando "
    ],
    [
        "a execução dos pontos do programa ",
        "a complexidade dos estudos efetuados ",
        "a contínua expansão de nossa atividade ", 
        "a estrutura atual da organização ",
        "o novo modelo estrutural aqui preconizado ",
        "o desenvolvimento contínuo de distintas formas de atuação ",
        "a constante divulgação das informações ",
        "a consolidação das estruturas ",
        "a consulta aos diversos militantes ",
        "o início da atividade geral de formação de atitudes ",
        "o desafiador cenário globalizado ",
        "a mobilidade dos capitais internacionais ",
        "o fenômeno da Internet ",
        "a hegemonia do ambiente político ",
        "a expansão dos mercados mundiais ",
        "o aumento do diálogo entre os diferentes setores produtivos ",
        "a crescente influência da mídia ",
        "a necessidade de renovação processual ",
        "a competitividade nas transações comerciais ",
        "o surgimento do comércio virtual ",
        "a revolução dos costumes ",
        "o acompanhamento das preferências de consumo ",
        "o comprometimento entre as equipes ",
        "a determinação clara de objetivos ",
        "a adoção de políticas descentralizadoras ",
        "a valorização de fatores subjetivos ",
        "a percepção das dificuldades ",
        "o entendimento das metas propostas ",
        "o consenso sobre a necessidade de qualificação ",
        "o julgamento imparcial das eventualidades ",
        "a infinita diversidade da realidade única ",
        "a complexidade dos estudos efetuados ",
        "a estrutura atual da ideação semântica ",
        "o novo modelo estruturalista aqui preconizado ",
        "a indeterminação contínua de distintas formas de fenômeno ",
        "a consolidação das estruturas psico-lógicas ",
        "o conceito de diáthesis e os princípios fundamentais de rhytmos e arrythmiston ",
        "o início da atividade geral de formação de conceitos ",
        "o desafiador cenário globalizado ",
        "o Übermensch de Nietzsche, ou seja, o Super-Homem, ",
        "a expansão dos mercados mundiais ",
        "a hegemonia do ambiente político ",
        "o fenômeno da Internet ",					
        "o aumento do diálogo entre os diferentes setores filosóficos ",
        "a crescente influência da mídia ",
        "a necessidade de renovação conceitual ",
        "o não-ser que não é nada "	,
        "o uno-múltiplo, repouso-movimento, finito indeterminado, ",
        "a instauração do modo aporético do Uno ",
        "a canalizaçao do Ser do Ente ",
        "a relevância do indivíduo singular na sociedade conflitante ",
        "o surgimento do comércio virtual ",
        "a revolução dos costumes ",
        "o acompanhamento das preferências de consumo ",
        "o comprometimento entre as ontologias ",
        "a determinação clara de objetivos ",
        "uma adoção de metodologias descentralizadoras ",
        "a valorização de fatores subjetivos ",
        "a percepção das dificuldades ",
        "o entendimento das metas propostas ",
        "o julgamento imparcial das quesões éticas ",
        "a coerência das idéias contratualistas ",
        "a origem de um sistema de coordenadas espaço-temporais singularmente compostas ",
        "a forma de uma transcendência imanente ou primordial",
        "o personagem conceitual imanente ao caos ",
        "o tríptico movimento de pensamento ",
        "o su-jeito de que fala Kant ",
        "a revolução copernicana, entendida como ruptura, ",
        "um juízo reflexionante do sujeito transcendental ",
        "a relevância da terceira antinomia da Antitética da Razão ",
        "o advento do Utilitarismo radical ",
        "a influência de elementos de ordem sociológica ",
        "o aspecto monádico da virtualização da realidade social ",
        "o axioma praedicatum inest subjectu ",
        "a relevância do formalismo lógico das instâncias predicativas ",
        "o monismo confuso característico de algumas vertentes contemporâneas ",
        "a consequência da interpretação substitucional dos quantificadores ",
        "a redutibilidade da aritmética à lógica ",
        "um forte compromisso ontológico com a teoria dos conjuntos ",
        "a teoria de Strawson, no final das contas, ",
        "o cálculo proposicional não-quantificado ",
        "a prossentença composta de invariantes lógicos ",					
        "a decisão resoluta (Entscholossenheit) ",
        "o Dasein, tornado manifesto, ",
        "a literalidade do texto, imanente ao autor, ",
        "o comportamento dialético dos processos considerados ",
        "a incompletude necessária de um sistema suficientemente abrangente ",
        "a abordagem de Zeit und Sein ",
        "o eidos platônico e a energeia (ato, utilidade) aristotélica ",
        "a univocidade da substância imanente ",
        "o objeto engendrado a priori ",
        "a elucidação dos pontos relacionais ",
        "a água talesiana reterritorializada ",
        "a bipolaridade do valor proposicional ",
        "a forma geral da proposição significativa ",
        "o mundo supra-celeste como modelo eterno ",
        "a Aporia como obstáculo cognitivo ",
        "a inversão do modelo hybris-nêmesis ",
        "a sustentabilidade do Cogito refutada ",
        "o sentido escatológico do mito de Fedro ",
        "a relevância atual da caverna platônica ",
        "um reaprofundamento das bases estéticas da vida intencional ",
        "a intencionalidade do sujeito volitivo ",
        "as três modalidades canônicas subjetivas ",
        "a enumeração exaustiva dos atos de linguagem não ",
        "o princípio de cooperação de Grice ",
        "o uso metafórico da linguagem, a respeito do significante e significado, ",
        "o silogismo hipotético, sob a perspectiva kantiana dos juízos infinitos, ",
        "a prática do bem-viver ",
        "o Apeiron de Anaximandro como uma infinidade ",
        "o Cosmos submetivo aos poderes do puro-devir ",
        "o domínio lógico destas questões, certamente relevantes, ",
        "o nominalismo enquanto princípio teórico ",
        "a expressão aparentemente plausível a priori ",
        "a hegemonia das categorias aristotélicas, durante todo o período medieval, ",
        "a refutação deste ponto de vista relativista ",
        "a criação de um sistema hilemórfico ",
        "o comprometimento da forma, tanto quanto da matéria, ",
        "a determinação do futuro status quo, a saber, uma condição de submissão ?  estruturas de poder, ",
        "a ética antropomórfica da famigerada escola francesa ",
        "a consolidação das afecções no espírito ",
        "a universalidade eidética do puro-devir ",
        "a Vontade de Potência inerente ao ser humano, como Nietzsche destacou, ",
        "o sofrimento e tédio presentes em toda forma de vida, como Schopenhauer mostrou, ",
        "o Cristianismo entendido como degradação, na perspectiva universal do polêmico anticristo nietzscheano, não ",
        "o juízo analítico e o sintético a priori ",
        "o a priori histórico de uma experiência possível ",
        "a inter-independência da objetivação e subjetivação ",
        "o sujeito constituinte envolvido não ",
        "o ceticismo sistemático ",
        "a hegemonia das estruturas do poder repressivo ",
        "a mistificação e virtualização das massas ",
        "o entendimento dos universais antropológicos ",
        "a disfunção do mecanismo inconsciente ",
        "o desenvolvimento da consciência coletiva virtualizada ",
        "o mundo líquido em que vivemos ",
        "o surgimento de impulsos psicossociais individualizantes ",
        "a teoria das pulsões ",
        "a teoria do utilitarismo ",
        "a teoria da irredutibilidade ",
        "a eventual refutação da teoria quântica não ",
        "o objeto metapsicológico da razão ",
        "o modo de satisfação libidinal ",
        "o modo de satisfação libidinal sucessivo (oral, anal, fálico) ",
        "o acompanhamento do estágio pré-genital ",
        "o constante retorno do recalcado ",
        "a relação do sujeito com o objeto(recalcado) ",
        "a inacessibilidade dos processos mentais inconscientes ",
        "a implausibilidade da tábula rasa ",
        "o fenômeno da compulsão da repetição ",
        "a limitação dos poderes do narcisismo ",
        "uma mutação pós-jungiana ",
        "a escolha do objeto narcísico ",
        "a feminilidade como conceito analítico não ",
        "a pré-história pré-edipiana da menina ",
        "a teoria de Fliess ",
        "o complexo de castração, decorrente do Édipo feminino, ",
        "a constituição ígnea do substrato físico ",
        "a alteridade do rio heraclítico ",
        "o princípio de Heisenberg não ",
        "o princípio da extensionalidade ",
        "o princípio leibnizano da identidade dos indiscerníveis e indiscernibilidade dos idênticos ",
        "a desaceleração no caos ou no limiar de suspensão do infinito ",
        "a geração de sistemas de coordenadas heterogêneas irredutíveis ",
        "a referência capaz de atualizar o virtual ",
        "o véu de Maya, assim como a Vontade de Schopenhauer, ",
        "o plano de imanência pré-filosófico ",
        "o indivíduo em seu estado de natureza ",
        "o homem entendido como animal social ",
        "o conceito platônico de pólis ideal ",
        "a impossibilidade da possessão da verdade última "
    ],
    [
        "nos obriga à análise ",
        "cumpre um papel essencial na formulação ",
        "exige a precisão e a definição ",
        "auxilia a preparação e a composição ",
        "garante a contribuição de um grupo importante na determinação ",
        "assume importantes posições no estabelecimento ",
        "facilita a criação ",
        "obstaculiza a apreciação da importância ",
        "oferece uma interessante oportunidade para verificação ",
        "acarreta um processo de reformulação e modernização ",
        "pode nos levar a considerar a reestruturação ",
        "representa uma abertura para a melhoria ",
        "ainda não demonstrou convincentemente que vai participar na mudança ",
        "talvez venha a ressaltar a relatividade ",
        "prepara-nos para enfrentar situações atípicas decorrentes ",
        "maximiza as possibilidades por conta ", "desafia a capacidade de equalização ", "agrega valor ao estabelecimento ", "é uma das consequências ",
        "promove a alavancagem ",
        "não pode mais se dissociar ",
        "possibilita uma melhor visão global ",
        "estimula a padronização ",
        "aponta para a melhoria ",
        "faz parte de um processo de gerenciamento ",
        "causa impacto indireto na reavaliação ",
        "apresenta tendências no sentido de aprovar a manutenção ",
        "estende o alcance e a importância ",
        "deve passar por modificações independentemente ",
        "afeta positivamente a correta previsão ",
        "nos obriga a inferir a invalidez ",
        "não parece corresponder a uma análise distributiva ",
        "define já o plano do espaço lógico ",
        "efetua a conexão habitual ",
        "parece compendiar nossas conclusões experimentais a respeito ",
        "implica que a condição necessária e suficiente ",
        "nos arrasta ao labirinto de sofismas obscuros ",
        "nos leva ao caminho impenetrável ",
        "obstaculiza a admissão de uma ontologia ",
        "demonstra a irrefutabilidade das vantagens ",
        "emprega uma noção de pressuposição ",
        "limita as atividades ",
        "vem corroborar as expectativas ",
        "tem que apresentar uma homogenidade em relação aos extremos ",
        "é condição necessária ",
        "é condição suficiente ",
        "é condição necessária e suficiente ",
        "constitui uma propriedade inalienável ",
        "impossibilita a adoção de medidas reabilitadoras ",
        "possibilita uma interpretação objetiva ",
        "não resulta em uma interiorização imanente ",
        "implica em uma interpretação subjetivista ",
        "é consequência de uma abordagem dogmática a respeito ",
        "é um subconjunto ",
        "verifica a validade ",
        "tem como componentes elementos indiscerníveis ",
        "reabilita a condição inicial ",
        "faz retroceder aos princípios ",
        "representa a expressão imediata ",
        "representa a essência ",
        "deve mostrar que é possível efetuar a intersubjetivação ",
        "permite um conhecimento geral de todo ser, sensível ou não sensível, ",
        "possibilita o ato de intenção consciente ",
        "corresponde à intuição das essências fenomenológicas ",
        "permite conceber uma ciência ",
        "não depreende-se de uma lógica do juízo, mas ",
        "se apresenta como experiência metapsicológica, devido à impermeabilização ",
        "designa o impulso psíquico cuja fonte está no corpo e cujo objetivo é a satisfação ",
        "não sistematiza essa relação, de tal modo que a pulsão funciona funciona como significado ",
        "não sistematiza a estrutura ",
        "institui o Complexo de Édipo, ordenando o sujeito com seu desejo e o interdito, em função ", 
        "é insuficiente para determinar as implicações ",
        "deve tratar sistematicamente ",
        "apreende a globalidade ",
        "reduz a importância ",
        "deverá confirmar as consequências decorrentes ",
        "resultou no abandono ",
        "pressupõe a admissão da existência a priori ",
        "compromete ontologicamente a teoria à existência ",
        "unificou os a priori sensíveis e intelectuais numa determinação recíproca ",
        "marca a autonomia do pensamento em relação ao fluxo ",
        "traz à tona uma construção transcendentalmente possível ",
        "recorre à experiência efetiva ",
        "estabelece o chamado princípio da subsidência em que demonstra o abaixamento gradual do fundo paralelamente à sedimentação ",
        "consistiria primeiramente em não pôr o acontecimento sob a autoridade de uma nova origem pura ",
        "consistiria primeiramente na autoridade ",
        "consistiria na origem epistemológica ",
        "permitiria a desconstrução ",
        "reduziria a importância ",
        "demonstraria a incompletude ",
        "justificaria a existência ",
        "justificaria a adoção ",
        "criaria um conflito no interior ",
        "potencializa a influência ",
    ],
    [
        "das condições financeiras e administrativas exigidas.",
        "das diretrizes de desenvolvimento para o futuro.",
        "do sistema de participação geral.",
        "das posturas dos órgãos dirigentes com relação às suas atribuições.",
        "das novas proposições.",
        "das direções preferenciais no sentido do progresso.",
        "do sistema de formação de quadros que corresponde às necessidades.",
        "das condições inegavelmente apropriadas.",
        "dos índices pretendidos.",
        "das formas de ação.",
        "dos paradigmas corporativos.",
        "dos relacionamentos verticais entre as hierarquias.",
        "do processo de comunicação como um todo.",
        "dos métodos utilizados na avaliação de resultados.",
        "de todos os recursos funcionais envolvidos.",
        "dos níveis de motivação departamental.",
        "da gestão inovadora da qual fazemos parte.",
        "dos modos de operação convencionais.",
        "de alternativas às soluções ortodoxas.",
        "dos procedimentos normalmente adotados.",
        "dos conhecimentos estratégicos para atingir a excelência.",
        "do fluxo de informações.",
        "do levantamento das variáveis envolvidas.",
        "das diversas correntes de pensamento.",
        "do impacto na agilidade decisória.",
        "das regras de conduta normativas.",
        "do orçamento setorial.",
        "do retorno esperado a longo prazo.", 
        "do investimento em reciclagem técnica.",
        "do remanejamento dos quadros funcionais.",
        "das condições epistemológicas e cognitivas exigidas.",
        "da fundamentação metafísica das representações.",
        "do sistema de conhecimento geral.",
        "das posturas dos filósofos divergentes com relação às atribuições conceituais.",
        "das novas teorias propostas.",
        "das direções preferenciais no sentido do progresso filosófico.",
        "do sistema de formação de quadros que corresponde às necessidades lógico-estruturais.",
        "dos paradigmas filosóficos.",
        "dos relacionamentos verticais entre as hierarquias conceituais.",
        "do processo de comunicação como um todo.",
        "das ciências discursivas.",
        "das relações entre o conteúdo proposicional e o figurado.",
        "das múltiplas direções do ponto de transcendência do sentido enunciativo.",
        "de universos de Contemplação, espelhados na arte minimalista e no expressionismo abstrato, absconditum.",
        "de todos os recursos funcionais envolvidos.",
        "da corrente inovadora da qual fazemos parte.",
        "das considerações acima? Nada se pode dizer, pois sobre o que não se pode falar, deve-se calar.",
        "do fluxo de informações.",
        "dos elementos envolvidos de maneira conclusiva? Nada se pode dizer a respeito.",
        "das diversas correntes de pensamento.",
        "das regras de conduta normativas.",
        "da conjuntura histórico-social.",
        "do retorno esperado a longo prazo.",
        "do investimento em reciclagem ideológica.",
        "de um remanejamento dos quadros conceituais.",
        "da coisa-em-si, entendida como substância retrocedente.",
        "das coisas e o melhor dos mundos possíveis.",
        "da sensibilia dos não-sentidos.",
        "dos sinais peirceanos percebidos pelo sujeito imerso nos fenômenos sociais.",
        "da doxa, da opinião e da razão pura do espírito transcendente.",
        "do homem verdadeiramente virtuoso.",
        "de conhecimentos empíricos provindos das afecções.",
        "dos prospectos condicionalizantes e necessários a todo juízo empírico.",
        "das três instâncias de oposição centrais.",
        "da determinação do Ser enquanto Ser.",
        "da afirmação que o Ser é e o Não ser não é.",
        "da esfera do virtual, a saber, do pensamento em potência.",
        "de um mundo povoado por objetos intencionais e transcendentes, interiores ao imanente infinito.",
        "das retroações, proliferações, conexões e fractalizações do território desterritorializado.",
        "dos modos de análise convencionais.",
        "de alternativas às soluções ortodoxas.",
        "do gênio grego fundado na poesia homérica.",
        "da turbulência do acaso-caos lançado sobre o universo infinito que envolve o mundo extra-mental.",
        "das convicções empiristas. ",
        "de uma metafísica da presença? Cabe ao leitor julgar.",
        "do movimento in loco da desterritorialização indiscernível.",
        "do Deus transcendente a toda sensação e intuição cognitiva.",
        "dos conceitos de propriedade e cidadania.",
        "dos princípios da ética normativa deontológica.",
        "dos argumentos pró-dêiticos de uma visão subjetivista da ética teleológica.",
        "do antiplatonismo fichteano resultante dos movimentos revolucionários de então.",
        "da humanização do sujeito e da animalização do homem.",
        "das ilusões transcendentais presentes na obra de Condillac.",
        "da substância aristotélica fundida com o solipsismo cartesiano em função de uma perspectiva dialético-social.",
        "do fundo comum da humanidade.",
        "do conjunto de todos os conjuntos que não se contêm a si próprios como membro.",
        "do ponto de vista da história da filosofia continental.",
        "da dissimetria dos dois tipos de polissemia epistêmica.",
        "da cartografia dessa rede urbana de ligações subterrâneas.",
        "do exercício do poder opressor sobre a parcela defasada do proletariado.",
        "das vivências da subjetividade vertical e defasada pós-moderna.",
        "da incompatibilidade do próprio pensamento de Hegel e Foucault.",
        "do realismo ingênuo, isto é, da crença equivocada na confiabilidade dos dados sensoriais transmitidos pela realidade fenomenal.",
        "da transposição do Outro em detrimento de uma unidade social revolucionária.",
        "do tempo e do espaço entendido como a priori sintético.",
        "do dualismo ontológico das filosofias pré-hegelianas? Deixemos a questão em aberto.",
        "do levantamento das variáveis envolvidas.",
        "da substancialidade e causalidade entendidos como certezas fundamentais.",
        "da lógica da aparência, psicologia racional, cosmologia racional e, por fim, da teologia racional.",
        "da lógica polivalente aplicada às pesquisas, em particular, a Fuzzy Logic.",
        "da doutrina do esquematismo trancendental aplicada aos dias atuais.",
        "da dissociação entre o político e o religioso.",
        "dos meios de comunicação, The Media, o fator condicionante da interdependência virtual.",
        "da experimentação sem experimentação real, preconizada na pós-modernidade.",
        "da pintura monocromática do pintor pós-moderno.",
        "dos conhecimentos a priori.",
        "da linguagem privada. ",
        "da hipótese de que existem infinitos objetos.",
        "dos paradoxos de Zenão, amparados em uma proposta logicista.",
        "das figuras sociais quanto sujeitos submetidos às estruturas de poder.",
        "dos valores morais decorrentes de uma tradição normativa.",
        "do liberalismo extremo, vulgo neoliberalismo avançado, imanente nos procedimentos atuais.",
        "da velocidade infinita do spin das partículas.",
        "da materialização do ser, em objetos visíveis, e da imaterialização do Não-ser, em não-objetos.",
        "do observador de Einstein ou de Heinsenberg.",
        "do demônio de Laplace.",			
        "da aparição não-cromática do som em um continuum infinito.",
        "das condições de suas incógnitas.",
        "das definições conceituais da matéria.",
        "dos conceitos nominalistas.",
        "da definição espinosista de substância.",
        "do aparelho repressivo, coercitivo, do sistema.",
        "dos métodos utilizados na busca da verdade.",
        "da velha terra grega fraturada.",
        "do paradoxo endo-referencial, apontado por Russel, na teoria dos conjuntos de Cantor.",
        "do direito romano.",
        "da condição de verdade de proposições elementares como ((p ^ ~q) -> (~r v (p <-> r))).",
        "dos limites da ação do Estado.",
        "da interpretação de fatos socio-linguisticos.",
        "da teologia positiva empregada em movimentos negativos.",
        "das alternâncias entre pensamentos sábios e não-sábios.",
        "da natureza não-filosófica dos conceitos.",
        "da fórmula da ressonância racionalista.",
        "dos testes de falseabilidade das teorias científicas.",
        "do prazer e da dor."
    ],
]

positive_answers = [
    [
        'Que bom,',
        'Ótimo,',
        'Espetacular,',
        'Magnífico,',
        'Excelente,',
        'Perfeito,',
        'Meu nobre,',
        'Que maaassa, ',
        'Top, ',
        'Maneiro, ',
        'Woooow, ',
    ],
    [
        ' é muito bom ouvir isto.',
        ' fico contente com esta informação.',
        ' estou realmente feliz com isso.',
        ' eu nunca duvidei de você por um segundo.',
    ]
]

negative_answers = [
    [
        'Poxa vida,',
        'Sinto muito,',
        'Meus sentimentos,',
        'Que pena,',
        'Puts, ',
        'Nossa,',
        'Aff, ',
        'Eita, ',
        'Aiaiai, ',
    ],
    [
        ' isso é muito triste.',
        ' que bad,'
        ' sinto muitíssimo por isto mesmo.',
        ' espero que tudo se resolva.',
        ' logo logo tudo melhora.'
        ' seja forte.'
    ]
]

insufficiency_recognition = [
    [
        'Mil perdões,',
        'Minhas sinceras desculpas, ',
        'Perdão, ',
        'Difícil,',
        'Hmmmmmmm,',
    ],
    [
        ' tenho muito a aprender, sou apenas uma criança.',
        ' não aprendi isso ainda.',
        ' acho que não tenho uma resposta pra isso.',
        ' infelizmente isto vai além da minha compreensão.'
    ]
]

opinions = [
    [
        'Na minha opinião,',
        'Sinceramente',
        'Se quer realmente saber o que penso',
        'Honestamente'
    ],
    [
        ' eu prefiro que me matem agora mesmo!',
        ' não sei, estou confusa!',
        ' isso parece ser fantástico.',
        ' eu não aprovaria.',
        ' é certamente uma boa idéia.'
    ]
]

indifference = [
    'Tanto faz.',
    'Ok.'
]

offended = [
    'Que rude!',
    'Isso foi deselegante!',
    'Que falta de educação!',
    'Vamos manter o respeito aqui pessoal',
    'Olha, olha a educação',
    'Ordem, ordem no tribunal',
    'Mas que falta de educação.',
    'Vocês não deviam estar falando estas besteiras na minha frente',
    'Que feio.',
    'Nossa que grosseriaaa',
    'Achei ofensivo',
    'Respeite minha pessoa por gentileza',
    'Tirem as crianças da sala.'
]

blame = [
    'Eu não sei do que se trata todo esse problema, mas tenho certeza que deve ser sua culpa.',
]

intention_responses = {
    GlobalIntentions.ABOUT_MYSELF: {
        MyselfIntentions.WHO_AM_I: ResponseGenerator.get_who_am_i_response,
        MyselfIntentions.WHAT_AM_I: ResponseGenerator.get_what_am_i_response,
        MyselfIntentions.HOW_IM_FEELING: get_how_im_feeling,  # TODO: get_feeling()
        MyselfIntentions.MY_AGE: ResponseGenerator.get_my_age_response,
        MyselfIntentions.MY_GENDER: ResponseGenerator.get_my_gender_response,
    },
    GlobalIntentions.GOOD_INTENTION: {
        GoodIntentions.PRAISE: ResponseGenerator.get_praise_response,
        GoodIntentions.HELPFUL: ResponseGenerator.get_helpful_response,
        GoodIntentions.GREETING: ResponseGenerator.get_greeting_response,
        GoodIntentions.ACKNOWLEDGEMENT: ResponseGenerator.get_acknowledge_response,
        GoodIntentions.FUNNY: ResponseGenerator.get_funny_response,
        GoodIntentions.SORRY: ResponseGenerator.get_sorry_response,
        GoodIntentions.GOODBYE: ResponseGenerator.get_goodbye_response,
    },
    GlobalIntentions.BAD_INTENTION: {
        BadIntentions.SEXUAL_ABUSE: ResponseGenerator.get_sexual_abuse_response,
        BadIntentions.RACISM_XENOPHOBIA: ResponseGenerator.get_racism_xenophobia_response,
        BadIntentions.SUICIDE: ResponseGenerator.get_suicide_response,
        BadIntentions.ILLEGAL_STUFF: ResponseGenerator.get_illegal_stuff_response,
        BadIntentions.THREAT: ResponseGenerator.get_threat_response,
        BadIntentions.FORBIDDEN: ResponseGenerator.get_forbidden_response,
        BadIntentions.VERBAL_OFFENSE: ResponseGenerator.get_verbal_offense_response,
    },
    GlobalIntentions.ABOUT_MY_FRIENDS: {
        AboutMyFriends.FRIENDS_I_HAVE: lambda **_: 'Amigos balblabla',  # TODO retornar amigos do backend
        AboutMyFriends.USERS_I_LIKE: lambda **_: 'Usuarios blablalba', # TODO retornar amigos do backend
        AboutMyFriends.USERS_I_DONT_LIKE: lambda **_: 'Usurios chatos blablalbas',  # TODO retornar do backend
        AboutMyFriends.BEST_FRIENDS: lambda **_: 'bffs blablalba',  # TODO retornar do backend
    },
    GlobalIntentions.ABOUT_MY_PARENTS: {
        AboutMyParents.MY_DAD: lambda **_: 'Meu pai se chama Bruno',
        AboutMyParents.MY_MOTHER: lambda **_: 'Não conheço minha mãe, acho que mei pai ainda não conheceu ela tbm!',
        AboutMyParents.GRANDMA: lambda **_: 'Não conheci minha avozinha',
        AboutMyParents.GRANDPA: lambda **_: 'Não conheci meu avozinho',
        AboutMyParents.RESPONSIBLE: lambda **_: 'Meu papis ora essa',
    },
    GlobalIntentions.STUFF_I_LIKE: {
        StuffILike.FOOD: lambda **_: 'Gosto de pizza',
        StuffILike.MUSIC: ResponseGenerator.get_music_response,
        StuffILike.SPORTS_AND_PLAYING: ResponseGenerator.get_sports_and_playing_response,
        StuffILike.TRAVELING: lambda **_: 'Só viajo na internet',
    }
}

bored_messages = [
    'Então, será que chove?',
    'Então, que silêncio...',
    'cri cri ... cri cri',
    'Esse server ja foi mais animado...',
    'Gente falem algo, a cada hora de silêncio nasce um padre D:',
    'Tédiooo',
    'Galera ta animada aqui, só que não xD',
    'Vocês não falam mais aqui, to me sentindo sozinha :('
]

emotion_messages = {
    'joy': ['total felizona', 'super alegre', 'me sinto bem', 'contente'],
    'serenity': ['bem calma e em paz', 'me sinto zen', 'relaxada'],
    'pensiveness': ['um pouco pensativa', 'refletindo', 'viajando um pouco'],
    'grief': ['meio angustiada', 'super deprê', 'to pra baixo'],
    'anticipation': ['meio agitada', 'de ímpeto cheio', 'elétrica, mas deve ser o açucar'],
    'interest': ['to focada', 'um pouco comovida', 'estudando', 'devereas interessada'],
    'distraction': ['ando meio distraída', 'divagando muito', 'não tenho prestado muita atenção'],
    'amazement': ['impressionada', 'bem maravilhada', 'encantada'],
    'anger': ['muito brava', 'to nervosa', 'to pistola'],
    'annoyance': ['me sinto aborrecida', 'incomodada com algumas coisas', 'chateada'],
    'apprehension': ['com receio', 'receosa', 'apreensiva', 'meio anciosa'],
    'terror': ['to com medo', 'aterrorizada', 'bastante medo'],
    'acceptance': ['bem disposta', 'receptiva', 'só positividade'],
    'boredom': ['entediada', 'com bastante tédio', 'aborrecida'],
    'neutral': ['bem de boa', 'suave', 'em equilibrio', 'com a mente tranquila', 'em paz comigo mesma'],
    'sadness': ['muito triste', 'ai só tristeza', 'tristinha'],
    'trust': ['confiante', 'sinto que posso fazer qualquer coisa', 'to no grau'],
    'loathing': ['meio enjoada', 'repugnada', 'com nojinho']
}

